package sqlglot

import "testing"

// ALTER TABLE ... SET in its many forms -- Redshift's location, file format
// and table properties, T-SQL's wrapped properties, the SET AUTHORIZATION and
// SET PROPERTIES statements the reference only reads as Commands, and
// ALTER COLUMN ... SET VISIBLE -- held to what the pinned reference writes.
func TestAlterSetForms(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET 'a' = '5'"},
		{"", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET 'a' = '1', LOCATION 'x'"},
		{"", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET LOCK_ESCALATION = AUTO"},
		{"", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET fillfactor = 70"},
		{"", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET autovacuum_enabled = FALSE, x = 1"},
		{"tsql", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (WITH (a=1))"},
		{"tsql", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"tsql", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"tsql", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"tsql", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET (WITH (LOCK_ESCALATION=AUTO))"},
		{"tsql", "ALTER TABLE t SET (SYSTEM_VERSIONING = ON)", "ALTER TABLE t SET (SYSTEM_VERSIONING=ON)"},
		{"tsql", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (WITH (a=1))"},
		{"tsql", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET (WITH (fillfactor=70))"},
		{"tsql", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET (WITH (autovacuum_enabled=(1 = 0), x=1))"},
		{"postgres", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"postgres", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"postgres", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"postgres", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"postgres", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"postgres", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"postgres", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET ('a' = '5')"},
		{"postgres", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (a = 1)"},
		{"postgres", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"postgres", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"postgres", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"postgres", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"postgres", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"postgres", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET ('a' = '1'), LOCATION 'x'"},
		{"postgres", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)"},
		{"postgres", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (a = 1)"},
		{"postgres", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET (fillfactor = 70)"},
		{"postgres", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET (autovacuum_enabled = FALSE, x = 1)"},
		{"duckdb", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"duckdb", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"duckdb", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"duckdb", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"duckdb", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"duckdb", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"duckdb", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET 'a' = '5'"},
		{"duckdb", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"duckdb", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"duckdb", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"duckdb", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"duckdb", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"duckdb", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"duckdb", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET 'a' = '1', LOCATION 'x'"},
		{"duckdb", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET LOCK_ESCALATION = AUTO"},
		{"duckdb", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"duckdb", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET fillfactor = 70"},
		{"duckdb", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET autovacuum_enabled = FALSE, x = 1"},
		{"databricks", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"databricks", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"databricks", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET LOCATION 's3://x'"},
		{"databricks", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET LOCATION loc"},
		{"databricks", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET FILEFORMAT parquet"},
		{"databricks", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET FILEFORMAT AVRO"},
		{"databricks", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET 'a' = '5'"},
		{"databricks", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"databricks", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"databricks", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"databricks", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"databricks", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"databricks", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"databricks", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET 'a' = '1', LOCATION 'x'"},
		{"databricks", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET LOCK_ESCALATION = AUTO"},
		{"databricks", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"databricks", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET fillfactor = 70"},
		{"databricks", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET autovacuum_enabled = FALSE, x = 1"},
		{"redshift", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"redshift", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"redshift", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET LOCATION 's3://x'"},
		{"redshift", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET LOCATION loc"},
		{"redshift", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET FILE FORMAT parquet"},
		{"redshift", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET FILE FORMAT AVRO"},
		{"redshift", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')"},
		{"redshift", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET TABLE PROPERTIES (a = 1)"},
		{"redshift", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"redshift", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"redshift", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"redshift", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"redshift", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"redshift", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '1'), LOCATION 'x'"},
		{"redshift", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET TABLE PROPERTIES (LOCK_ESCALATION = AUTO)"},
		{"redshift", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET TABLE PROPERTIES (a = 1)"},
		{"redshift", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET TABLE PROPERTIES (fillfactor = 70)"},
		{"redshift", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET TABLE PROPERTIES (autovacuum_enabled = FALSE, x = 1)"},
		{"materialize", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"materialize", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"materialize", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"materialize", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"materialize", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"materialize", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"materialize", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET ('a' = '5')"},
		{"materialize", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (a = 1)"},
		{"materialize", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"materialize", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"materialize", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"materialize", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"materialize", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"materialize", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET ('a' = '1'), LOCATION 'x'"},
		{"materialize", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)"},
		{"materialize", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (a = 1)"},
		{"materialize", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET (fillfactor = 70)"},
		{"materialize", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET (autovacuum_enabled = FALSE, x = 1)"},
		{"risingwave", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"risingwave", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"risingwave", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"risingwave", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"risingwave", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"risingwave", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"risingwave", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET ('a' = '5')"},
		{"risingwave", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (a = 1)"},
		{"risingwave", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"risingwave", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"risingwave", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"risingwave", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"risingwave", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"risingwave", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET ('a' = '1'), LOCATION 'x'"},
		{"risingwave", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)"},
		{"risingwave", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (a = 1)"},
		{"risingwave", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET (fillfactor = 70)"},
		{"risingwave", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET (autovacuum_enabled = FALSE, x = 1)"},
		{"fabric", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (WITH (a=1))"},
		{"fabric", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"fabric", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"fabric", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"fabric", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET (WITH (LOCK_ESCALATION=AUTO))"},
		{"fabric", "ALTER TABLE t SET (SYSTEM_VERSIONING = ON)", "ALTER TABLE t SET (SYSTEM_VERSIONING=ON)"},
		{"fabric", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET (WITH (a=1))"},
		{"fabric", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET (WITH (fillfactor=70))"},
		{"fabric", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET (WITH (autovacuum_enabled=(1 = 0), x=1))"},
		{"presto", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"presto", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"presto", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"presto", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"presto", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"presto", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"presto", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET 'a' = '5'"},
		{"presto", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"presto", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"presto", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"presto", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"presto", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"presto", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"presto", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET 'a' = '1', LOCATION 'x'"},
		{"presto", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET LOCK_ESCALATION = AUTO"},
		{"presto", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"presto", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET fillfactor = 70"},
		{"presto", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET autovacuum_enabled = FALSE, x = 1"},
		{"trino", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"trino", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"trino", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"trino", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"trino", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"trino", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"trino", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET 'a' = '5'"},
		{"trino", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"trino", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"trino", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"trino", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"trino", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"trino", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"trino", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET 'a' = '1', LOCATION='x'"},
		{"trino", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET LOCK_ESCALATION = AUTO"},
		{"trino", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"trino", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET fillfactor = 70"},
		{"trino", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET autovacuum_enabled = FALSE, x = 1"},
		{"dremio", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"dremio", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"dremio", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"dremio", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"dremio", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"dremio", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"dremio", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET 'a' = '5'"},
		{"dremio", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"dremio", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"dremio", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"dremio", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"dremio", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"dremio", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"dremio", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET 'a' = '1', LOCATION 'x'"},
		{"dremio", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET LOCK_ESCALATION = AUTO"},
		{"dremio", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"dremio", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET fillfactor = 70"},
		{"dremio", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET autovacuum_enabled = FALSE, x = 1"},
		{"mysql", "ALTER TABLE t SET AUTHORIZATION a", "ALTER TABLE t SET AUTHORIZATION a"},
		{"mysql", "ALTER TABLE t SET PROPERTIES a = 1", "ALTER TABLE t SET PROPERTIES a = 1"},
		{"mysql", "ALTER TABLE t SET LOCATION 's3://x'", "ALTER TABLE t SET"},
		{"mysql", "ALTER TABLE t SET LOCATION loc", "ALTER TABLE t SET"},
		{"mysql", "ALTER TABLE t SET FILEFORMAT parquet", "ALTER TABLE t SET"},
		{"mysql", "ALTER TABLE t SET FILE FORMAT AVRO", "ALTER TABLE t SET"},
		{"mysql", "ALTER TABLE t SET TABLE PROPERTIES ('a' = '5')", "ALTER TABLE t SET 'a' = '5'"},
		{"mysql", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"mysql", "ALTER TABLE t ALTER COLUMN c SET VISIBLE", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"mysql", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE", "ALTER TABLE t ALTER COLUMN c SET INVISIBLE"},
		{"mysql", "ALTER TABLE t ALTER c SET visible", "ALTER TABLE t ALTER COLUMN c SET VISIBLE"},
		{"mysql", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r", "ALTER TABLE IF EXISTS t SET AUTHORIZATION ROLE r"},
		{"mysql", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO", "ALTER TABLE t SET LOCATION 's3://x' FILE FORMAT AVRO"},
		{"mysql", "ALTER TABLE t SET TABLE PROPERTIES ('a'='1') LOCATION 'x'", "ALTER TABLE t SET 'a' = '1', LOCATION 'x'"},
		{"mysql", "ALTER TABLE t SET (LOCK_ESCALATION = AUTO)", "ALTER TABLE t SET LOCK_ESCALATION = AUTO"},
		{"mysql", "ALTER TABLE t SET (a = 1)", "ALTER TABLE t SET a = 1"},
		{"mysql", "ALTER TABLE t SET (fillfactor = 70)", "ALTER TABLE t SET fillfactor = 70"},
		{"mysql", "ALTER TABLE t SET (autovacuum_enabled = false, x = 1)", "ALTER TABLE t SET autovacuum_enabled = FALSE, x = 1"},
	} {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written < 40 {
		t.Errorf("only %d statements were written back", written)
	}
	for _, sql := range []string{
		"ALTER TABLE t SET LOCATION",
		"ALTER TABLE t SET LOCATION 1",
		"ALTER TABLE t SET FILE FORMAT",
		"ALTER TABLE t SET FILEFORMAT",
		"ALTER TABLE t SET TABLE PROPERTIES",
		"ALTER TABLE t SET TABLE PROPERTIES (",
		"ALTER TABLE t ALTER COLUMN c SET",
		"ALTER TABLE t SET AUTHORIZATION",
	} {
		for _, d := range []string{"redshift", "postgres", "tsql", "mysql", "trino"} {
			if tree, err := ParseOne(sql, d); err == nil && tree != nil {
				_, _ = Generate(tree, d)
			}
		}
	}
}
