package sqlglot

import "testing"

// MySQL's ZEROFILL and INVISIBLE, Redshift's ENCODE, Trino's LISTAGG ... ON
// OVERFLOW and ANALYZE's histograms, column sets and properties, held to what
// the pinned reference writes.
func TestConstraintsOverflowAndAnalyze(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"", "CREATE TABLE t (a INT ENCODE ZSTD)", "CREATE TABLE t (a INT ENCODE ZSTD)"},
		{"", "CREATE TABLE t (a INT ENCODE raw NOT NULL)", "CREATE TABLE t (a INT ENCODE raw NOT NULL)"},
		{"", "ALTER TABLE t ADD COLUMN c INT INVISIBLE", "ALTER TABLE t ADD COLUMN c INT INVISIBLE"},
		{"", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD"},
		{"", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t"},
		{"", "SELECT STRING_AGG(x, ',' ON OVERFLOW ERROR ORDER BY y) FROM t", "SELECT GROUP_CONCAT(x ORDER BY y, ',') FROM t"},
		{"", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t"},
		{"", "ANALYZE tbl UPDATE HISTOGRAM ON col1", "ANALYZE tbl UPDATE HISTOGRAM ON col1"},
		{"", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS"},
		{"", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE"},
		{"", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE"},
		{"", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'"},
		{"", "ANALYZE tbl DROP HISTOGRAM ON col1", "ANALYZE tbl DROP HISTOGRAM ON col1"},
		{"", "ANALYZE tbl DROP HISTOGRAM ON col1, col2", "ANALYZE tbl DROP HISTOGRAM ON col1, col2"},
		{"", "ANALYZE TBL PREDICATE COLUMNS", "ANALYZE TBL PREDICATE COLUMNS"},
		{"", "ANALYZE TBL ALL COLUMNS", "ANALYZE TBL ALL COLUMNS"},
		{"", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS"},
		{"", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c"},
		{"", "ANALYZE tbl WITH (prop1=val1, prop2=val2)", "ANALYZE tbl WITH (prop1=val1, prop2=val2)"},
		{"postgres", "CREATE TABLE t (a INT ENCODE ZSTD)", "CREATE TABLE t (a INT ENCODE ZSTD)"},
		{"postgres", "CREATE TABLE t (a INT ENCODE raw NOT NULL)", "CREATE TABLE t (a INT ENCODE raw NOT NULL)"},
		{"postgres", "ALTER TABLE t ADD COLUMN c INT INVISIBLE", "ALTER TABLE t ADD COLUMN c INT INVISIBLE"},
		{"postgres", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD"},
		{"postgres", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t"},
		{"postgres", "SELECT STRING_AGG(x, ',' ON OVERFLOW ERROR ORDER BY y) FROM t", "SELECT STRING_AGG(x, ',' ORDER BY y) FROM t"},
		{"postgres", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t"},
		{"postgres", "ANALYZE tbl UPDATE HISTOGRAM ON col1", "ANALYZE tbl UPDATE HISTOGRAM ON col1"},
		{"postgres", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS"},
		{"postgres", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE"},
		{"postgres", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE"},
		{"postgres", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'"},
		{"postgres", "ANALYZE tbl DROP HISTOGRAM ON col1", "ANALYZE tbl DROP HISTOGRAM ON col1"},
		{"postgres", "ANALYZE tbl DROP HISTOGRAM ON col1, col2", "ANALYZE tbl DROP HISTOGRAM ON col1, col2"},
		{"postgres", "ANALYZE TBL PREDICATE COLUMNS", "ANALYZE TBL PREDICATE COLUMNS"},
		{"postgres", "ANALYZE TBL ALL COLUMNS", "ANALYZE TBL ALL COLUMNS"},
		{"postgres", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS"},
		{"postgres", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c"},
		{"postgres", "ANALYZE tbl WITH (prop1=val1, prop2=val2)", "ANALYZE tbl WITH (prop1=val1, prop2=val2)"},
		{"redshift", "CREATE TABLE t (a INT ENCODE ZSTD)", "CREATE TABLE t (a INTEGER ENCODE ZSTD)"},
		{"redshift", "CREATE TABLE t (a INT ENCODE raw NOT NULL)", "CREATE TABLE t (a INTEGER ENCODE raw NOT NULL)"},
		{"redshift", "ALTER TABLE t ADD COLUMN c INT INVISIBLE", "ALTER TABLE t ADD COLUMN c INT INVISIBLE"},
		{"redshift", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD", "ALTER TABLE t ADD COLUMN c INTEGER ENCODE ZSTD"},
		{"redshift", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t"},
		{"redshift", "SELECT STRING_AGG(x, ',' ON OVERFLOW ERROR ORDER BY y) FROM t", "SELECT LISTAGG(x ORDER BY y, ',') FROM t"},
		{"redshift", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t"},
		{"redshift", "ANALYZE tbl UPDATE HISTOGRAM ON col1", "ANALYZE tbl UPDATE HISTOGRAM ON col1"},
		{"redshift", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS"},
		{"redshift", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE"},
		{"redshift", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE"},
		{"redshift", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'"},
		{"redshift", "ANALYZE tbl DROP HISTOGRAM ON col1", "ANALYZE tbl DROP HISTOGRAM ON col1"},
		{"redshift", "ANALYZE tbl DROP HISTOGRAM ON col1, col2", "ANALYZE tbl DROP HISTOGRAM ON col1, col2"},
		{"redshift", "ANALYZE TBL PREDICATE COLUMNS", "ANALYZE TBL PREDICATE COLUMNS"},
		{"redshift", "ANALYZE TBL ALL COLUMNS", "ANALYZE TBL ALL COLUMNS"},
		{"redshift", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS"},
		{"redshift", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c"},
		{"redshift", "ANALYZE tbl WITH (prop1=val1, prop2=val2)", "ANALYZE tbl  (prop1=val1, prop2=val2)"},
		{"presto", "CREATE TABLE t (a INT ENCODE ZSTD)", "CREATE TABLE t (a INTEGER ENCODE ZSTD)"},
		{"presto", "CREATE TABLE t (a INT ENCODE raw NOT NULL)", "CREATE TABLE t (a INTEGER ENCODE raw NOT NULL)"},
		{"presto", "ALTER TABLE t ADD COLUMN c INT INVISIBLE", "ALTER TABLE t ADD COLUMN c INT INVISIBLE"},
		{"presto", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD", "ALTER TABLE t ADD COLUMN c INTEGER ENCODE ZSTD"},
		{"presto", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t"},
		{"presto", "SELECT STRING_AGG(x, ',' ON OVERFLOW ERROR ORDER BY y) FROM t", "SELECT ARRAY_JOIN(ARRAY_AGG(x ORDER BY y), ',') FROM t"},
		{"presto", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t"},
		{"presto", "ANALYZE tbl UPDATE HISTOGRAM ON col1", "ANALYZE tbl UPDATE HISTOGRAM ON col1"},
		{"presto", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS"},
		{"presto", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE"},
		{"presto", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE"},
		{"presto", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'"},
		{"presto", "ANALYZE tbl DROP HISTOGRAM ON col1", "ANALYZE tbl DROP HISTOGRAM ON col1"},
		{"presto", "ANALYZE tbl DROP HISTOGRAM ON col1, col2", "ANALYZE tbl DROP HISTOGRAM ON col1, col2"},
		{"presto", "ANALYZE TBL PREDICATE COLUMNS", "ANALYZE TBL PREDICATE COLUMNS"},
		{"presto", "ANALYZE TBL ALL COLUMNS", "ANALYZE TBL ALL COLUMNS"},
		{"presto", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS"},
		{"presto", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c"},
		{"presto", "ANALYZE tbl WITH (prop1=val1, prop2=val2)", "ANALYZE tbl WITH (prop1=val1, prop2=val2)"},
		{"trino", "CREATE TABLE t (a INT ENCODE ZSTD)", "CREATE TABLE t (a INTEGER ENCODE ZSTD)"},
		{"trino", "CREATE TABLE t (a INT ENCODE raw NOT NULL)", "CREATE TABLE t (a INTEGER ENCODE raw NOT NULL)"},
		{"trino", "ALTER TABLE t ADD COLUMN c INT INVISIBLE", "ALTER TABLE t ADD COLUMN c INT INVISIBLE"},
		{"trino", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD", "ALTER TABLE t ADD COLUMN c INTEGER ENCODE ZSTD"},
		{"trino", "SELECT LISTAGG(x, ',' ON OVERFLOW ERROR) WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',' ON OVERFLOW ERROR) WITHIN GROUP (ORDER BY y) FROM t"},
		{"trino", "SELECT LISTAGG(x, ',' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',' ON OVERFLOW TRUNCATE WITH COUNT) WITHIN GROUP (ORDER BY y) FROM t"},
		{"trino", "SELECT LISTAGG(x ON OVERFLOW TRUNCATE '..' WITHOUT COUNT) WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',' ON OVERFLOW TRUNCATE '..' WITHOUT COUNT) WITHIN GROUP (ORDER BY y) FROM t"},
		{"trino", "SELECT LISTAGG(x, ',' ON OVERFLOW ERROR) FROM t", "SELECT LISTAGG(x, ',') FROM t"},
		{"trino", "SELECT LISTAGG(DISTINCT x, ',' ON OVERFLOW TRUNCATE WITH COUNT) WITHIN GROUP (ORDER BY x) FROM t", "SELECT LISTAGG(DISTINCT x, ',' ON OVERFLOW TRUNCATE WITH COUNT) WITHIN GROUP (ORDER BY x) FROM t"},
		{"trino", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t"},
		{"trino", "SELECT STRING_AGG(x, ',' ON OVERFLOW ERROR ORDER BY y) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t"},
		{"trino", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y DESC) FROM t"},
		{"trino", "SELECT LISTAGG(x, ',' ON OVERFLOW) WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',' ON OVERFLOW TRUNCATE WITH COUNT) WITHIN GROUP (ORDER BY y) FROM t"},
		{"trino", "ANALYZE tbl UPDATE HISTOGRAM ON col1", "ANALYZE tbl UPDATE HISTOGRAM ON col1"},
		{"trino", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS"},
		{"trino", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE"},
		{"trino", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE"},
		{"trino", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'"},
		{"trino", "ANALYZE tbl DROP HISTOGRAM ON col1", "ANALYZE tbl DROP HISTOGRAM ON col1"},
		{"trino", "ANALYZE tbl DROP HISTOGRAM ON col1, col2", "ANALYZE tbl DROP HISTOGRAM ON col1, col2"},
		{"trino", "ANALYZE TBL PREDICATE COLUMNS", "ANALYZE TBL PREDICATE COLUMNS"},
		{"trino", "ANALYZE TBL ALL COLUMNS", "ANALYZE TBL ALL COLUMNS"},
		{"trino", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS"},
		{"trino", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c"},
		{"trino", "ANALYZE tbl WITH (prop1=val1, prop2=val2)", "ANALYZE tbl WITH (prop1=val1, prop2=val2)"},
		{"mysql", "CREATE TABLE t (a INT ENCODE ZSTD)", "CREATE TABLE t (a INT ENCODE ZSTD)"},
		{"mysql", "CREATE TABLE t (a INT ENCODE raw NOT NULL)", "CREATE TABLE t (a INT ENCODE raw NOT NULL)"},
		{"mysql", "CREATE TABLE t (a INT ZEROFILL)", "CREATE TABLE t (a INT ZEROFILL)"},
		{"mysql", "CREATE TABLE t (a INT(5) UNSIGNED ZEROFILL NOT NULL)", "CREATE TABLE t (a INT(5) UNSIGNED ZEROFILL NOT NULL)"},
		{"mysql", "CREATE TABLE t (a INT INVISIBLE NOT NULL)", "CREATE TABLE t (a INT INVISIBLE NOT NULL)"},
		{"mysql", "CREATE TABLE t (a INT NOT NULL INVISIBLE DEFAULT 1)", "CREATE TABLE t (a INT NOT NULL INVISIBLE DEFAULT 1)"},
		{"mysql", "ALTER TABLE t ADD COLUMN c INT INVISIBLE", "ALTER TABLE t ADD COLUMN c INT INVISIBLE"},
		{"mysql", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD", "ALTER TABLE t ADD COLUMN c INT ENCODE ZSTD"},
		{"mysql", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t", "SELECT LISTAGG(x, ',') WITHIN GROUP (ORDER BY y) FROM t"},
		{"mysql", "SELECT STRING_AGG(x, ',' ON OVERFLOW ERROR ORDER BY y) FROM t", "SELECT GROUP_CONCAT(x ORDER BY y SEPARATOR ',') FROM t"},
		{"mysql", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY y DESC) FROM t"},
		{"mysql", "ANALYZE tbl UPDATE HISTOGRAM ON col1", "ANALYZE tbl UPDATE HISTOGRAM ON col1"},
		{"mysql", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1, col2 WITH 5 BUCKETS"},
		{"mysql", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS AUTO UPDATE"},
		{"mysql", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS MANUAL UPDATE"},
		{"mysql", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'", "ANALYZE tbl UPDATE HISTOGRAM ON col1 USING DATA 'json'"},
		{"mysql", "ANALYZE tbl DROP HISTOGRAM ON col1", "ANALYZE tbl DROP HISTOGRAM ON col1"},
		{"mysql", "ANALYZE tbl DROP HISTOGRAM ON col1, col2", "ANALYZE tbl DROP HISTOGRAM ON col1, col2"},
		{"mysql", "ANALYZE TBL PREDICATE COLUMNS", "ANALYZE TBL PREDICATE COLUMNS"},
		{"mysql", "ANALYZE TBL ALL COLUMNS", "ANALYZE TBL ALL COLUMNS"},
		{"mysql", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS", "ANALYZE tbl UPDATE HISTOGRAM ON col1 WITH 5 BUCKETS WITH 6 BUCKETS"},
		{"mysql", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c", "ANALYZE t1, t2 UPDATE HISTOGRAM ON c"},
		{"mysql", "ANALYZE tbl WITH (prop1=val1, prop2=val2)", "ANALYZE tbl WITH (prop1=val1, prop2=val2)"},
	} {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written < 80 {
		t.Errorf("only %d statements were written back", written)
	}
	for _, sql := range []string{
		"ANALYZE tbl UPDATE HISTOGRAM ON",
		"ANALYZE tbl UPDATE HISTOGRAM ON c WITH",
		"ANALYZE tbl UPDATE HISTOGRAM ON c WITH 5",
		"ANALYZE tbl UPDATE HISTOGRAM ON c WITH SYNC MODE",
		"ANALYZE tbl UPDATE HISTOGRAM ON c USING DATA",
		"ANALYZE tbl UPDATE HISTOGRAM ON c AUTO",
		"ANALYZE tbl ALL",
		"ANALYZE tbl WITH (",
		"SELECT LISTAGG(x ON OVERFLOW",
		"SELECT LISTAGG(x ON OVERFLOW TRUNCATE 'a' WITH",
		"CREATE TABLE t (a INT ENCODE)",
		"CREATE TABLE t (a INT ZEROFILL",
	} {
		for _, d := range []string{"mysql", "trino", "redshift"} {
			if tree, err := ParseOne(sql, d); err == nil && tree != nil {
				_, _ = Generate(tree, d)
			}
		}
	}
	tree, err := ParseOne("SELECT LISTAGG(x, ',' ON OVERFLOW ERROR) WITHIN GROUP (ORDER BY y) FROM t", "trino")
	if err != nil {
		t.Fatal(err)
	}
	if out, err := Generate(tree, "postgres"); err == nil {
		t.Errorf("another dialect wrote an overflow behaviour: %s", out)
	}
}
