// Code generated by harness/gen_annotate.py from the pinned reference. DO NOT EDIT.
//
// Which types widen into which. The annotator resolves a binary
// operator by asking whether one side coerces into the other; this is
// the reference's own COERCES_TO, which is a table rather than a
// closure and so is emitted rather than probed.

package sqlglot

var coercesTo = map[string]map[string]bool{
	"BIGDECIMAL": {
		"DECFLOAT": true,
		"DOUBLE":   true,
		"FLOAT":    true,
	},
	"BIGINT": {
		"BIGDECIMAL": true,
		"DECFLOAT":   true,
		"DECIMAL":    true,
		"DOUBLE":     true,
		"FLOAT":      true,
	},
	"CHAR": {
		"NCHAR":    true,
		"NVARCHAR": true,
		"TEXT":     true,
		"VARCHAR":  true,
	},
	"DATE": {
		"DATETIME":     true,
		"TIMESTAMP":    true,
		"TIMESTAMPLTZ": true,
		"TIMESTAMPTZ":  true,
	},
	"DATETIME": {
		"TIMESTAMP":    true,
		"TIMESTAMPLTZ": true,
		"TIMESTAMPTZ":  true,
	},
	"DECFLOAT": {},
	"DECIMAL": {
		"BIGDECIMAL": true,
		"DECFLOAT":   true,
		"DOUBLE":     true,
		"FLOAT":      true,
	},
	"DOUBLE": {
		"DECFLOAT": true,
	},
	"FLOAT": {
		"DECFLOAT": true,
		"DOUBLE":   true,
	},
	"INT": {
		"BIGDECIMAL": true,
		"BIGINT":     true,
		"DECFLOAT":   true,
		"DECIMAL":    true,
		"DOUBLE":     true,
		"FLOAT":      true,
	},
	"NCHAR": {
		"NVARCHAR": true,
		"TEXT":     true,
		"VARCHAR":  true,
	},
	"NVARCHAR": {
		"TEXT": true,
	},
	"SMALLINT": {
		"BIGDECIMAL": true,
		"BIGINT":     true,
		"DECFLOAT":   true,
		"DECIMAL":    true,
		"DOUBLE":     true,
		"FLOAT":      true,
		"INT":        true,
	},
	"TEXT": {},
	"TIMESTAMP": {
		"TIMESTAMPLTZ": true,
		"TIMESTAMPTZ":  true,
	},
	"TIMESTAMPLTZ": {},
	"TIMESTAMPTZ": {
		"TIMESTAMPLTZ": true,
	},
	"TINYINT": {
		"BIGDECIMAL": true,
		"BIGINT":     true,
		"DECFLOAT":   true,
		"DECIMAL":    true,
		"DOUBLE":     true,
		"FLOAT":      true,
		"INT":        true,
		"SMALLINT":   true,
	},
	"VARCHAR": {
		"NVARCHAR": true,
		"TEXT":     true,
	},
}

// supportsNullType: where false, a NULL-typed node ends as UNKNOWN.
// Databricks is the exception, and spells the surviving type VOID.
var supportsNullType = map[string]bool{
	"":           false,
	"databricks": true,
	"duckdb":     false,
	"postgres":   false,
	"tsql":       false,
}
