package sqlglot

import "testing"

// IDENTITY(seed, step) is read positionally where no START WITH came first; a
// lone number is the seed. Both write back in the keyword form of the target.
// A parse or generate error fails the row.
func TestIdentityPositional(t *testing.T) {
	cases := [][3]string{
		{"redshift", "CREATE TABLE t (c BIGINT GENERATED BY DEFAULT AS IDENTITY (0, 1))", "CREATE TABLE t (c BIGINT IDENTITY(0, 1))"},
		{"redshift", "CREATE TABLE t (c BIGINT GENERATED BY DEFAULT AS IDENTITY (7))", "CREATE TABLE t (c BIGINT IDENTITY(7, 1))"},
		{"postgres", "CREATE TABLE t (c BIGINT GENERATED BY DEFAULT AS IDENTITY (7))", "CREATE TABLE t (c BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7))"},
		{"postgres", "CREATE TABLE t (c BIGINT GENERATED ALWAYS AS IDENTITY (5, 2))", "CREATE TABLE t (c BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 5 INCREMENT BY 2))"},
		{"postgres", "CREATE TABLE t (c BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 INCREMENT BY 1))", "CREATE TABLE t (c BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 INCREMENT BY 1))"},
	}
	written := 0
	for _, c := range cases {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			t.Errorf("[%s] ParseOne(%q): %v", c[0], c[1], err)
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			t.Errorf("[%s] Generate(%q): %v", c[0], c[1], err)
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written != len(cases) {
		t.Errorf("wrote %d statements, want %d", written, len(cases))
	}
}
