package sqlglot

import "testing"

// Materialize's LIST and MAP[K => V] types, which the base parser reads in
// every dialect, and the type rules around them: MySQL's nested spellings
// and CAST sizes, DuckDB dropping only the OUTERMOST text length, Databricks
// reading CHAR/VARCHAR as STRING outside a schema, and T-SQL's sized TEXT.
// What the port writes must be what the pinned reference writes.
func TestListMapTypes(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"tsql", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS LIST<INTEGER>)"},
		{"tsql", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS LIST<LIST<LIST<INTEGER>>>)"},
		{"tsql", "SELECT MAP['a' => 1, 'b' => 2]", "SELECT MAP AS ['a' => 1, 'b' => 2]"},
		{"tsql", "SELECT MAP[]", "SELECT MAP AS []"},
		{"tsql", "SELECT LIST[1]", "SELECT LIST AS [1]"},
		{"tsql", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"tsql", "SELECT x::INT LIST", "SELECT CAST(x AS LIST<INTEGER>)"},
		{"tsql", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP) AS [TEXT => INT]"},
		{"tsql", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS VARCHAR(3))"},
		{"tsql", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)"},
		{"tsql", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP<VARCHAR(3), INTEGER>)"},
		{"tsql", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS ARRAY<INTEGER>)"},
		{"tsql", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP<VARCHAR(MAX), INTEGER>)"},
		{"tsql", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a ARRAY<INTEGER>)"},
		{"tsql", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT<a INTEGER>)"},
		{"tsql", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS INTEGER(11))"},
		{"tsql", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS VARCHAR(MAX)(10))"},
		{"tsql", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS CHAR(3))"},
		{"tsql", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS NUMERIC)"},
		{"tsql", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS ARRAY<NUMERIC>)"},
		{"tsql", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"tsql", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)"},
		{"tsql", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS ARRAY<LIST<INTEGER>>)"},
		{"tsql", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t ALTER COLUMN a VARCHAR(3)"},
		{"tsql", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) AS RETURN a"},
		{"postgres", "SELECT CAST(LIST[1, 2, 3] AS INT LIST)", "SELECT CAST(LIST(1, 2, 3) AS LIST<INT>)"},
		{"postgres", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS LIST<INT>)"},
		{"postgres", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS LIST<LIST<LIST<INT>>>)"},
		{"postgres", "SELECT CAST(NULL AS MAP[TEXT => INT])", "SELECT CAST(NULL AS MAP<TEXT, INT>)"},
		{"postgres", "SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])", "SELECT CAST(NULL AS MAP<TEXT, MAP<TEXT, INT>>)"},
		{"postgres", "SELECT CAST(NULL AS INT LIST[])", "SELECT CAST(NULL AS LIST<INT>[])"},
		{"postgres", "SELECT CAST(NULL AS MAP[TEXT => INT LIST])", "SELECT CAST(NULL AS MAP<TEXT, LIST<INT>>)"},
		{"postgres", "CREATE TABLE t (a INT LIST, b MAP[TEXT => INT])", "CREATE TABLE t (a LIST<INT>, b MAP<TEXT, INT>)"},
		{"postgres", "SELECT LIST[1]", "SELECT LIST(1)"},
		{"postgres", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"postgres", "SELECT x::INT LIST", "SELECT CAST(x AS LIST<INT>)"},
		{"postgres", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP<TEXT, INT>)"},
		{"postgres", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS VARCHAR(3))"},
		{"postgres", "SELECT CAST(x AS VARCHAR(3)[])", "SELECT CAST(x AS VARCHAR(3)[])"},
		{"postgres", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS VARCHAR(3)[])"},
		{"postgres", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)"},
		{"postgres", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS INT[])"},
		{"postgres", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP<TEXT, INT>)"},
		{"postgres", "SELECT CAST(x AS INT[])", "SELECT CAST(x AS INT[])"},
		{"postgres", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a INT[])"},
		{"postgres", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT<a INT>)"},
		{"postgres", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS INT(11))"},
		{"postgres", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS TEXT(10))"},
		{"postgres", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS CHAR(3))"},
		{"postgres", "SELECT CAST(x AS DECIMAL[])", "SELECT CAST(x AS DECIMAL[])"},
		{"postgres", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS DECIMAL)"},
		{"postgres", "SELECT CAST(x AS NUMERIC[])", "SELECT CAST(x AS DECIMAL[])"},
		{"postgres", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS DECIMAL[])"},
		{"postgres", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"postgres", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)"},
		{"postgres", "CREATE TABLE t (a VARCHAR(3)[], b ARRAY<CHAR(2)>)", "CREATE TABLE t (a VARCHAR(3)[], b CHAR(2)[])"},
		{"postgres", "SELECT CAST(x AS MAP[INT => INT])", "SELECT CAST(x AS MAP<INT, INT>)"},
		{"postgres", "SELECT CAST(x AS MAP [INT => INT])", "SELECT CAST(x AS MAP<INT, INT>)"},
		{"postgres", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS LIST<INT>[])"},
		{"postgres", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t ALTER COLUMN a SET DATA TYPE VARCHAR(3)"},
		{"postgres", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) AS RETURN a"},
		{"duckdb", "SELECT CAST(LIST[1, 2, 3] AS INT LIST)", "SELECT CAST(LIST[1, 2, 3] AS LIST(INT))"},
		{"duckdb", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS LIST(INT))"},
		{"duckdb", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS LIST(LIST(LIST(INT))))"},
		{"duckdb", "SELECT CAST(NULL AS MAP[TEXT => INT])", "SELECT CAST(NULL AS MAP(TEXT, INT))"},
		{"duckdb", "SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])", "SELECT CAST(NULL AS MAP(TEXT, MAP(TEXT, INT)))"},
		{"duckdb", "SELECT CAST(NULL AS INT LIST[])", "SELECT CAST(NULL AS LIST(INT)[])"},
		{"duckdb", "SELECT CAST(NULL AS MAP[TEXT => INT LIST])", "SELECT CAST(NULL AS MAP(TEXT, LIST(INT)))"},
		{"duckdb", "CREATE TABLE t (a INT LIST, b MAP[TEXT => INT])", "CREATE TABLE t (a LIST(INT), b MAP(TEXT, INT))"},
		{"duckdb", "SELECT LIST[1]", "SELECT LIST[1]"},
		{"duckdb", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST(TEXT(3)))"},
		{"duckdb", "SELECT x::INT LIST", "SELECT CAST(x AS LIST(INT))"},
		{"duckdb", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP(TEXT, INT))"},
		{"duckdb", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS TEXT)"},
		{"duckdb", "SELECT CAST(x AS VARCHAR(3)[])", "SELECT CAST(x AS TEXT(3)[])"},
		{"duckdb", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS TEXT[])"},
		{"duckdb", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP(TEXT, INT))"},
		{"duckdb", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS INT[])"},
		{"duckdb", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP(TEXT, INT))"},
		{"duckdb", "SELECT CAST(x AS INT[])", "SELECT CAST(x AS INT[])"},
		{"duckdb", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a INT[])"},
		{"duckdb", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT(a INT))"},
		{"duckdb", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS INT(11))"},
		{"duckdb", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS TEXT)"},
		{"duckdb", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS TEXT)"},
		{"duckdb", "SELECT CAST(x AS DECIMAL[])", "SELECT CAST(x AS DECIMAL[])"},
		{"duckdb", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS DECIMAL(18, 3))"},
		{"duckdb", "SELECT CAST(x AS NUMERIC[])", "SELECT CAST(x AS DECIMAL[])"},
		{"duckdb", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS DECIMAL(18, 3)[])"},
		{"duckdb", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST(TEXT(3)))"},
		{"duckdb", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT(a TEXT))"},
		{"duckdb", "CREATE TABLE t (a VARCHAR(3)[], b ARRAY<CHAR(2)>)", "CREATE TABLE t (a TEXT(3)[], b TEXT[])"},
		{"duckdb", "SELECT CAST(x AS MAP[INT => INT])", "SELECT CAST(x AS MAP(INT, INT))"},
		{"duckdb", "SELECT CAST(x AS MAP [INT => INT])", "SELECT CAST(x AS MAP(INT, INT))"},
		{"duckdb", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS LIST(INT)[])"},
		{"duckdb", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t ALTER COLUMN a SET DATA TYPE TEXT"},
		{"databricks", "SELECT CAST(LIST[1, 2, 3] AS INT LIST)", "SELECT CAST(LIST(1, 2, 3) AS LIST<INT>)"},
		{"databricks", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS LIST<INT>)"},
		{"databricks", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS LIST<LIST<LIST<INT>>>)"},
		{"databricks", "SELECT CAST(NULL AS MAP[TEXT => INT])", "SELECT CAST(NULL AS MAP<STRING, INT>)"},
		{"databricks", "SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])", "SELECT CAST(NULL AS MAP<STRING, MAP<STRING, INT>>)"},
		{"databricks", "SELECT CAST(NULL AS INT LIST[])", "SELECT CAST(NULL AS ARRAY<LIST<INT>>)"},
		{"databricks", "SELECT CAST(NULL AS MAP[TEXT => INT LIST])", "SELECT CAST(NULL AS MAP<STRING, LIST<INT>>)"},
		{"databricks", "CREATE TABLE t (a INT LIST, b MAP[TEXT => INT])", "CREATE TABLE t (a LIST<INT>, b MAP<STRING, INT>)"},
		{"databricks", "SELECT LIST[1]", "SELECT LIST(1)"},
		{"databricks", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<STRING>)"},
		{"databricks", "SELECT x::INT LIST", "SELECT CAST(x AS LIST<INT>)"},
		{"databricks", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP<STRING, INT>)"},
		{"databricks", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS STRING)"},
		{"databricks", "SELECT CAST(x AS VARCHAR(3)[])", "SELECT CAST(x AS ARRAY<STRING>)"},
		{"databricks", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS ARRAY<STRING>)"},
		{"databricks", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP<STRING, INT>)"},
		{"databricks", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS ARRAY<INT>)"},
		{"databricks", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP<STRING, INT>)"},
		{"databricks", "SELECT CAST(x AS INT[])", "SELECT CAST(x AS ARRAY<INT>)"},
		{"databricks", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a ARRAY<INT>)"},
		{"databricks", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT<a: INT>)"},
		{"databricks", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS INT(11))"},
		{"databricks", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS VARCHAR(10))"},
		{"databricks", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS STRING)"},
		{"databricks", "SELECT CAST(x AS DECIMAL[])", "SELECT CAST(x AS ARRAY<DECIMAL>)"},
		{"databricks", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS DECIMAL)"},
		{"databricks", "SELECT CAST(x AS NUMERIC[])", "SELECT CAST(x AS ARRAY<DECIMAL>)"},
		{"databricks", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS ARRAY<DECIMAL>)"},
		{"databricks", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<STRING>)"},
		{"databricks", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT<a: STRING>)"},
		{"databricks", "CREATE TABLE t (a VARCHAR(3)[], b ARRAY<CHAR(2)>)", "CREATE TABLE t (a ARRAY<VARCHAR(3)>, b ARRAY<CHAR(2)>)"},
		{"databricks", "SELECT CAST(x AS MAP[INT => INT])", "SELECT CAST(x AS MAP<INT, INT>)"},
		{"databricks", "SELECT CAST(x AS MAP [INT => INT])", "SELECT CAST(x AS MAP<INT, INT>)"},
		{"databricks", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS ARRAY<LIST<INT>>)"},
		{"databricks", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t ALTER COLUMN a TYPE STRING"},
		{"databricks", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS STRING RETURN a"},
		{"redshift", "SELECT CAST(LIST[1, 2, 3] AS INT LIST)", "SELECT CAST(LIST(1, 2, 3) AS LIST<INTEGER>)"},
		{"redshift", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS LIST<INTEGER>)"},
		{"redshift", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS LIST<LIST<LIST<INTEGER>>>)"},
		{"redshift", "SELECT CAST(NULL AS MAP[TEXT => INT])", "SELECT CAST(NULL AS MAP<VARCHAR(MAX), INTEGER>)"},
		{"redshift", "SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])", "SELECT CAST(NULL AS MAP<VARCHAR(MAX), MAP<VARCHAR(MAX), INTEGER>>)"},
		{"redshift", "SELECT CAST(NULL AS INT LIST[])", "SELECT CAST(NULL AS LIST<INTEGER>[])"},
		{"redshift", "SELECT CAST(NULL AS MAP[TEXT => INT LIST])", "SELECT CAST(NULL AS MAP<VARCHAR(MAX), LIST<INTEGER>>)"},
		{"redshift", "CREATE TABLE t (a INT LIST, b MAP[TEXT => INT])", "CREATE TABLE t (a LIST<INTEGER>, b MAP<VARCHAR(MAX), INTEGER>)"},
		{"redshift", "SELECT LIST[1]", "SELECT LIST(1)"},
		{"redshift", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"redshift", "SELECT x::INT LIST", "SELECT CAST(x AS LIST<INTEGER>)"},
		{"redshift", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP<VARCHAR(MAX), INTEGER>)"},
		{"redshift", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS VARCHAR(3))"},
		{"redshift", "SELECT CAST(x AS VARCHAR(3)[])", "SELECT CAST(x AS VARCHAR(3)[])"},
		{"redshift", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS VARCHAR(3)[])"},
		{"redshift", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP<VARCHAR(3), INTEGER>)"},
		{"redshift", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS INTEGER[])"},
		{"redshift", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP<VARCHAR(MAX), INTEGER>)"},
		{"redshift", "SELECT CAST(x AS INT[])", "SELECT CAST(x AS INTEGER[])"},
		{"redshift", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a INTEGER[])"},
		{"redshift", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT<a INTEGER>)"},
		{"redshift", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS INTEGER(11))"},
		{"redshift", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS VARCHAR(10))"},
		{"redshift", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS CHAR(3))"},
		{"redshift", "SELECT CAST(x AS DECIMAL[])", "SELECT CAST(x AS DECIMAL[])"},
		{"redshift", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS DECIMAL)"},
		{"redshift", "SELECT CAST(x AS NUMERIC[])", "SELECT CAST(x AS DECIMAL[])"},
		{"redshift", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS DECIMAL[])"},
		{"redshift", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"redshift", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)"},
		{"redshift", "CREATE TABLE t (a VARCHAR(3)[], b ARRAY<CHAR(2)>)", "CREATE TABLE t (a VARCHAR(3)[], b CHAR(2)[])"},
		{"redshift", "SELECT CAST(x AS MAP[INT => INT])", "SELECT CAST(x AS MAP<INTEGER, INTEGER>)"},
		{"redshift", "SELECT CAST(x AS MAP [INT => INT])", "SELECT CAST(x AS MAP<INTEGER, INTEGER>)"},
		{"redshift", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS LIST<INTEGER>[])"},
		{"redshift", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)"},
		{"redshift", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) AS RETURN a"},
		{"materialize", "SELECT CAST(LIST[1, 2, 3] AS INT LIST)", "SELECT CAST(LIST[1, 2, 3] AS INT LIST)"},
		{"materialize", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS INT LIST)"},
		{"materialize", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS INT LIST LIST LIST)"},
		{"materialize", "SELECT CAST(MAP['a' => 1] AS MAP[TEXT => INT])", "SELECT CAST(MAP['a' => 1] AS MAP[TEXT => INT])"},
		{"materialize", "SELECT CAST(NULL AS MAP[TEXT => INT])", "SELECT CAST(NULL AS MAP[TEXT => INT])"},
		{"materialize", "SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])", "SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])"},
		{"materialize", "SELECT CAST(NULL AS INT LIST[])", "SELECT CAST(NULL AS INT LIST[])"},
		{"materialize", "SELECT CAST(NULL AS MAP[TEXT => INT LIST])", "SELECT CAST(NULL AS MAP[TEXT => INT LIST])"},
		{"materialize", "CREATE TABLE t (a INT LIST, b MAP[TEXT => INT])", "CREATE TABLE t (a INT LIST, b MAP[TEXT => INT])"},
		{"materialize", "SELECT MAP['a' => 1, 'b' => 2]", "SELECT MAP['a' => 1, 'b' => 2]"},
		{"materialize", "SELECT MAP[]", "SELECT MAP[]"},
		{"materialize", "SELECT LIST[1]", "SELECT LIST[1]"},
		{"materialize", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS VARCHAR(3) LIST)"},
		{"materialize", "SELECT x::INT LIST", "SELECT CAST(x AS INT LIST)"},
		{"materialize", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP[TEXT => INT])"},
		{"materialize", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS VARCHAR(3))"},
		{"materialize", "SELECT CAST(x AS VARCHAR(3)[])", "SELECT CAST(x AS VARCHAR(3)[])"},
		{"materialize", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS VARCHAR(3)[])"},
		{"materialize", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP[VARCHAR(3) => INT])"},
		{"materialize", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS INT[])"},
		{"materialize", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP[TEXT => INT])"},
		{"materialize", "SELECT CAST(x AS INT[])", "SELECT CAST(x AS INT[])"},
		{"materialize", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a INT[])"},
		{"materialize", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT<a INT>)"},
		{"materialize", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS INT(11))"},
		{"materialize", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS TEXT(10))"},
		{"materialize", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS CHAR(3))"},
		{"materialize", "SELECT CAST(x AS DECIMAL[])", "SELECT CAST(x AS DECIMAL[])"},
		{"materialize", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS DECIMAL)"},
		{"materialize", "SELECT CAST(x AS NUMERIC[])", "SELECT CAST(x AS DECIMAL[])"},
		{"materialize", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS DECIMAL[])"},
		{"materialize", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS VARCHAR(3) LIST)"},
		{"materialize", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)"},
		{"materialize", "CREATE TABLE t (a VARCHAR(3)[], b ARRAY<CHAR(2)>)", "CREATE TABLE t (a VARCHAR(3)[], b CHAR(2)[])"},
		{"materialize", "SELECT CAST(x AS MAP[INT => INT])", "SELECT CAST(x AS MAP[INT => INT])"},
		{"materialize", "SELECT CAST(x AS MAP [INT => INT])", "SELECT CAST(x AS MAP[INT => INT])"},
		{"materialize", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS INT LIST[])"},
		{"materialize", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t ALTER COLUMN a SET DATA TYPE VARCHAR(3)"},
		{"materialize", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) AS RETURN a"},
		{"fabric", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS LIST<INT>)"},
		{"fabric", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS LIST<LIST<LIST<INT>>>)"},
		{"fabric", "SELECT MAP['a' => 1, 'b' => 2]", "SELECT MAP AS ['a' => 1, 'b' => 2]"},
		{"fabric", "SELECT MAP[]", "SELECT MAP AS []"},
		{"fabric", "SELECT LIST[1]", "SELECT LIST AS [1]"},
		{"fabric", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"fabric", "SELECT x::INT LIST", "SELECT CAST(x AS LIST<INT>)"},
		{"fabric", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP) AS [TEXT => INT]"},
		{"fabric", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS VARCHAR(3))"},
		{"fabric", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)"},
		{"fabric", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)"},
		{"fabric", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS ARRAY<INT>)"},
		{"fabric", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP<VARCHAR(MAX), INT>)"},
		{"fabric", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a ARRAY<INT>)"},
		{"fabric", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT<a INT>)"},
		{"fabric", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS INT(11))"},
		{"fabric", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS VARCHAR(MAX)(10))"},
		{"fabric", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS CHAR(3))"},
		{"fabric", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS DECIMAL)"},
		{"fabric", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS ARRAY<DECIMAL>)"},
		{"fabric", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"fabric", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)"},
		{"fabric", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS ARRAY<LIST<INT>>)"},
		{"fabric", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t ALTER COLUMN a VARCHAR(3)"},
		{"fabric", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) AS RETURN a"},
		{"mysql", "SELECT CAST(LIST[1, 2, 3] AS INT LIST)", "SELECT CAST(LIST(1, 2, 3) AS LIST<INT>)"},
		{"mysql", "SELECT CAST(NULL AS INT LIST)", "SELECT CAST(NULL AS LIST<INT>)"},
		{"mysql", "SELECT CAST(NULL AS INT LIST LIST LIST)", "SELECT CAST(NULL AS LIST<LIST<LIST<INT>>>)"},
		{"mysql", "SELECT CAST(NULL AS MAP[TEXT => INT])", "SELECT CAST(NULL AS MAP<TEXT, INT>)"},
		{"mysql", "SELECT CAST(NULL AS MAP[TEXT => MAP[TEXT => INT]])", "SELECT CAST(NULL AS MAP<TEXT, MAP<TEXT, INT>>)"},
		{"mysql", "SELECT CAST(NULL AS INT LIST[])", "SELECT CAST(NULL AS ARRAY<LIST<INT>>)"},
		{"mysql", "SELECT CAST(NULL AS MAP[TEXT => INT LIST])", "SELECT CAST(NULL AS MAP<TEXT, LIST<INT>>)"},
		{"mysql", "CREATE TABLE t (a INT LIST, b MAP[TEXT => INT])", "CREATE TABLE t (a LIST<INT>, b MAP<TEXT, INT>)"},
		{"mysql", "SELECT LIST[1]", "SELECT LIST(1)"},
		{"mysql", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"mysql", "SELECT x::INT LIST", "SELECT CAST(x AS LIST<INT>)"},
		{"mysql", "SELECT x::MAP[TEXT => INT]", "SELECT CAST(x AS MAP<TEXT, INT>)"},
		{"mysql", "SELECT CAST(x AS VARCHAR(3))", "SELECT CAST(x AS CHAR(3))"},
		{"mysql", "SELECT CAST(x AS VARCHAR(3)[])", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)"},
		{"mysql", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)", "SELECT CAST(x AS ARRAY<VARCHAR(3)>)"},
		{"mysql", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)", "SELECT CAST(x AS MAP<VARCHAR(3), INT>)"},
		{"mysql", "SELECT CAST(x AS ARRAY<INT>)", "SELECT CAST(x AS ARRAY<INT>)"},
		{"mysql", "SELECT CAST(x AS MAP<TEXT, INT>)", "SELECT CAST(x AS MAP<TEXT, INT>)"},
		{"mysql", "SELECT CAST(x AS INT[])", "SELECT CAST(x AS ARRAY<INT>)"},
		{"mysql", "CREATE TABLE t (a ARRAY<INT>)", "CREATE TABLE t (a ARRAY<INT>)"},
		{"mysql", "SELECT CAST(x AS STRUCT<a INT>)", "SELECT CAST(x AS STRUCT<a INT>)"},
		{"mysql", "SELECT CAST(x AS INT(11))", "SELECT CAST(x AS SIGNED(11))"},
		{"mysql", "SELECT CAST(x AS TEXT(10))", "SELECT CAST(x AS CHAR(10))"},
		{"mysql", "SELECT CAST(x AS CHAR(3))", "SELECT CAST(x AS CHAR(3))"},
		{"mysql", "SELECT CAST(x AS DECIMAL[])", "SELECT CAST(x AS ARRAY<DECIMAL>)"},
		{"mysql", "SELECT CAST(x AS NUMERIC)", "SELECT CAST(x AS DECIMAL)"},
		{"mysql", "SELECT CAST(x AS NUMERIC[])", "SELECT CAST(x AS ARRAY<DECIMAL>)"},
		{"mysql", "SELECT CAST(x AS ARRAY<NUMERIC>)", "SELECT CAST(x AS ARRAY<DECIMAL>)"},
		{"mysql", "SELECT CAST(x AS VARCHAR(3) LIST)", "SELECT CAST(x AS LIST<VARCHAR(3)>)"},
		{"mysql", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)", "SELECT CAST(x AS STRUCT<a VARCHAR(3)>)"},
		{"mysql", "CREATE TABLE t (a VARCHAR(3)[], b ARRAY<CHAR(2)>)", "CREATE TABLE t (a ARRAY<VARCHAR(3)>, b ARRAY<CHAR(2)>)"},
		{"mysql", "SELECT CAST(x AS MAP[INT => INT])", "SELECT CAST(x AS MAP<INT, INT>)"},
		{"mysql", "SELECT CAST(x AS MAP [INT => INT])", "SELECT CAST(x AS MAP<INT, INT>)"},
		{"mysql", "SELECT CAST(x AS INT LIST ARRAY)", "SELECT CAST(x AS ARRAY<LIST<INT>>)"},
		{"mysql", "ALTER TABLE t ALTER COLUMN a TYPE VARCHAR(3)", "ALTER TABLE t MODIFY COLUMN a VARCHAR(3)"},
		{"mysql", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a", "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) AS RETURN a"},
	} {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			t.Errorf("[%s] ParseOne(%q): %v", c[0], c[1], err)
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			t.Errorf("[%s] Generate(%q): %v", c[0], c[1], err)
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written != 268 {
		t.Errorf("wrote %d statements, want 268", written)
	}
	// DuckDB writes a function's return type nowhere. Emitting the function
	// without RETURNS would promise less than the statement did, so the
	// generator declines.
	fn := "CREATE FUNCTION f(a VARCHAR(3)) RETURNS VARCHAR(3) RETURN a"
	tree, err := ParseOne(fn, "duckdb")
	if err != nil {
		t.Fatalf("ParseOne(%q): %v", fn, err)
	}
	if _, err := Generate(tree, "duckdb"); err == nil {
		t.Error("DuckDB wrote a function whose RETURNS it cannot place")
	}
}
