package sqlglot

import "testing"

// MySQL's index and key ALTER actions, UPDATE ... ORDER BY/LIMIT and
// multi-table DELETE, held to what the pinned reference writes.
func TestMySQLAlterUpdateDelete(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX SET DATA TYPE i"},
		{"", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"tsql", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"tsql", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"tsql", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"tsql", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"tsql", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX i"},
		{"tsql", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"tsql", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"tsql", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"tsql", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"tsql", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"tsql", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"tsql", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"tsql", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"tsql", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"tsql", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"tsql", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"tsql", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"tsql", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"postgres", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"postgres", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"postgres", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"postgres", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"postgres", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX SET DATA TYPE i"},
		{"postgres", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"postgres", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"postgres", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"postgres", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"postgres", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"postgres", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"postgres", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"postgres", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"postgres", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"postgres", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"postgres", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"postgres", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"postgres", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"duckdb", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"duckdb", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"duckdb", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"duckdb", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"duckdb", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX SET DATA TYPE i"},
		{"duckdb", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"duckdb", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"duckdb", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"duckdb", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"duckdb", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"duckdb", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"duckdb", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"duckdb", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"duckdb", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1, t2, t3 WHERE t1.id = t2.id"},
		{"duckdb", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"duckdb", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1, t2, t3 WHERE t1.id = t2.id"},
		{"duckdb", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"duckdb", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"databricks", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"databricks", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"databricks", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"databricks", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"databricks", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER INDEX i"},
		{"databricks", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"databricks", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"databricks", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"databricks", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"databricks", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"databricks", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"databricks", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"databricks", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"databricks", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 ON TRUE INNER JOIN t3 ON TRUE WHERE t1.id = t2.id"},
		{"databricks", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"databricks", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1 CROSS JOIN t2 USING t1 INNER JOIN t2 ON TRUE INNER JOIN t3 ON TRUE WHERE t1.id = t2.id"},
		{"databricks", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"databricks", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"redshift", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"redshift", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"redshift", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"redshift", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"redshift", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER INDEX i"},
		{"redshift", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"redshift", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"redshift", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"redshift", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"redshift", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"redshift", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"redshift", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"redshift", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"redshift", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"redshift", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"redshift", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"redshift", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"redshift", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"materialize", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"materialize", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"materialize", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"materialize", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"materialize", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX SET DATA TYPE i"},
		{"materialize", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"materialize", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"materialize", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"materialize", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"materialize", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"materialize", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"materialize", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"materialize", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"materialize", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"materialize", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"materialize", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"materialize", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"materialize", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"risingwave", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"risingwave", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"risingwave", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"risingwave", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"risingwave", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX SET DATA TYPE i"},
		{"risingwave", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"risingwave", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"risingwave", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"risingwave", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"risingwave", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"risingwave", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"risingwave", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"risingwave", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"risingwave", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"risingwave", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"risingwave", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"risingwave", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"risingwave", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"fabric", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"fabric", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"fabric", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"fabric", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"fabric", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX i"},
		{"fabric", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"fabric", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"fabric", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"fabric", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"fabric", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"fabric", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"fabric", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"fabric", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"fabric", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"fabric", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"fabric", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"fabric", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"fabric", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"presto", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"presto", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"presto", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"presto", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"presto", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER COLUMN INDEX SET DATA TYPE i"},
		{"presto", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"presto", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"presto", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"presto", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"presto", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"presto", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"presto", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"presto", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"presto", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"presto", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE FROM t1 WHERE t2.id IS NULL"},
		{"presto", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"presto", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"presto", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"trino", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"trino", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"trino", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"trino", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"trino", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER INDEX i"},
		{"trino", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"trino", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"trino", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"trino", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"trino", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"trino", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"trino", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"trino", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"trino", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"trino", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE FROM t1 WHERE t2.id IS NULL"},
		{"trino", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"trino", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"trino", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"dremio", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"dremio", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME KEY a b"},
		{"dremio", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"dremio", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"dremio", "ALTER TABLE t ALTER INDEX i", "ALTER TABLE t ALTER INDEX i"},
		{"dremio", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"dremio", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"dremio", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"dremio", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"dremio", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"dremio", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"dremio", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"dremio", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"dremio", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"dremio", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"dremio", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"dremio", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"dremio", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
		{"mysql", "ALTER TABLE t RENAME INDEX a TO b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"mysql", "ALTER TABLE t RENAME KEY a b", "ALTER TABLE t RENAME INDEX a TO b"},
		{"mysql", "ALTER TABLE t ALTER INDEX i INVISIBLE", "ALTER TABLE t ALTER INDEX i INVISIBLE"},
		{"mysql", "ALTER TABLE t ALTER INDEX i VISIBLE", "ALTER TABLE t ALTER INDEX i VISIBLE"},
		{"mysql", "ALTER TABLE t DROP PRIMARY KEY", "ALTER TABLE t DROP PRIMARY KEY"},
		{"mysql", "ALTER TABLE t DROP INDEX i", "ALTER TABLE t DROP INDEX i"},
		{"mysql", "ALTER TABLE t DROP INDEX `i`", "ALTER TABLE t DROP INDEX `i`"},
		{"mysql", "ALTER TABLE t DROP FOREIGN KEY fk", "ALTER TABLE t DROP FOREIGN KEY fk"},
		{"mysql", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i", "ALTER TABLE t DROP COLUMN c, DROP PRIMARY KEY, DROP INDEX i"},
		{"mysql", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10", "UPDATE items SET price = 0 WHERE id >= 5 ORDER BY id LIMIT 10"},
		{"mysql", "UPDATE t SET a = 1 ORDER BY b DESC", "UPDATE t SET a = 1 ORDER BY b DESC"},
		{"mysql", "UPDATE t SET a = 1 LIMIT 2", "UPDATE t SET a = 1 LIMIT 2"},
		{"mysql", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"mysql", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL", "DELETE t1 FROM t1 LEFT JOIN t2 ON t1.id = t2.id WHERE t2.id IS NULL"},
		{"mysql", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id", "DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id = t2.id"},
		{"mysql", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1", "DELETE FROM t1 JOIN t2 ON t1.a = t2.a WHERE t2.b = 1"},
		{"mysql", "DELETE FROM t WHERE a = 1", "DELETE FROM t WHERE a = 1"},
	} {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written < 90 {
		t.Errorf("only %d statements were written back", written)
	}
	for _, sql := range []string{
		"ALTER TABLE t RENAME INDEX",
		"ALTER TABLE t RENAME INDEX a TO",
		"ALTER TABLE t ALTER INDEX",
		"ALTER TABLE t DROP INDEX",
		"ALTER TABLE t DROP FOREIGN KEY",
		"UPDATE t SET a = 1 ORDER BY",
		"UPDATE t SET a = 1 LIMIT",
		"DELETE t1 FROM t1 JOIN",
	} {
		if tree, err := ParseOne(sql, "mysql"); err == nil && tree != nil {
			_, _ = Generate(tree, "mysql")
		}
	}
}
