package sqlglot

import "testing"

// INSERT IGNORE, character set introducers, CAST ... CHARACTER SET, computed
// columns, SOUNDS LIKE and MATCH ... AGAINST modifiers, held to what the
// pinned reference writes in every dialect.
func TestMySQLMisc(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT AS (a + a) PERSISTED)"},
		{"", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT AS (a * 2))"},
		{"", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT AS (a * 2) NOT NULL)"},
		{"", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT AS ((a * 2)) PERSISTED)"},
		{"", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"tsql", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"tsql", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"tsql", "SELECT _utf8mb4 'hola'", "SELECT _utf8mb4 AS [hola]"},
		{"tsql", "SELECT _utf8mb4'a'", "SELECT _utf8mb4 AS [a]"},
		{"tsql", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"tsql", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"tsql", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"tsql", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"tsql", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"tsql", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INTEGER, b AS (a + a) PERSISTED)"},
		{"tsql", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INTEGER, b AS (a * 2))"},
		{"tsql", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INTEGER, b AS (a * 2) NOT NULL)"},
		{"tsql", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INTEGER, b AS ((a * 2)) PERSISTED)"},
		{"tsql", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"tsql", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"tsql", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"tsql", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"tsql", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"postgres", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"postgres", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"postgres", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"postgres", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"postgres", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"postgres", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"postgres", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"postgres", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a + a)) STORED)"},
		{"postgres", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a * 2)) STORED)"},
		{"postgres", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a * 2)) STORED NOT NULL)"},
		{"postgres", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (((a * 2))) STORED)"},
		{"postgres", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT (a @@ 'abc' OR b @@ 'abc')"},
		{"postgres", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"postgres", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"postgres", "SELECT MATCH(a) AGAINST('abc')", "SELECT a @@ 'abc'"},
		{"postgres", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT a @@ 'abc'"},
		{"duckdb", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"duckdb", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"duckdb", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"duckdb", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS TEXT)"},
		{"duckdb", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT AS (a + a) PERSISTED)"},
		{"duckdb", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT AS (a * 2))"},
		{"duckdb", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT AS (a * 2) NOT NULL)"},
		{"duckdb", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT AS ((a * 2)) PERSISTED)"},
		{"duckdb", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"duckdb", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"duckdb", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"duckdb", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"duckdb", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"databricks", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"databricks", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"databricks", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"databricks", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS STRING)"},
		{"databricks", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a + a)))"},
		{"databricks", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a * 2)))"},
		{"databricks", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a * 2)) NOT NULL)"},
		{"databricks", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (((a * 2))))"},
		{"databricks", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"databricks", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"databricks", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"databricks", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"databricks", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"redshift", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"redshift", "INSERT IGNORE", "INSERT INTO \"IGNORE\""},
		{"redshift", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"redshift", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"redshift", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"redshift", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"redshift", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"redshift", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INTEGER, b INTEGER GENERATED ALWAYS AS ((a + a)) STORED)"},
		{"redshift", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INTEGER, b INTEGER GENERATED ALWAYS AS ((a * 2)) STORED)"},
		{"redshift", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INTEGER, b INTEGER GENERATED ALWAYS AS ((a * 2)) STORED NOT NULL)"},
		{"redshift", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INTEGER, b INTEGER GENERATED ALWAYS AS (((a * 2))) STORED)"},
		{"redshift", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT (a @@ 'abc' OR b @@ 'abc')"},
		{"redshift", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"redshift", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"redshift", "SELECT MATCH(a) AGAINST('abc')", "SELECT a @@ 'abc'"},
		{"redshift", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT a @@ 'abc'"},
		{"materialize", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"materialize", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"materialize", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"materialize", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"materialize", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"materialize", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"materialize", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"materialize", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a + a)) STORED)"},
		{"materialize", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a * 2)) STORED)"},
		{"materialize", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS ((a * 2)) STORED NOT NULL)"},
		{"materialize", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (((a * 2))) STORED)"},
		{"materialize", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT (a @@ 'abc' OR b @@ 'abc')"},
		{"materialize", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"materialize", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"materialize", "SELECT MATCH(a) AGAINST('abc')", "SELECT a @@ 'abc'"},
		{"materialize", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT a @@ 'abc'"},
		{"risingwave", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"risingwave", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"risingwave", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"risingwave", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"risingwave", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"risingwave", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"risingwave", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"risingwave", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT AS (a + a) PERSISTED)"},
		{"risingwave", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT AS (a * 2))"},
		{"risingwave", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT AS (a * 2) NOT NULL)"},
		{"risingwave", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT AS ((a * 2)) PERSISTED)"},
		{"risingwave", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT (a @@ 'abc' OR b @@ 'abc')"},
		{"risingwave", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"risingwave", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT a @@ 'abc'"},
		{"risingwave", "SELECT MATCH(a) AGAINST('abc')", "SELECT a @@ 'abc'"},
		{"risingwave", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT a @@ 'abc'"},
		{"fabric", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"fabric", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"fabric", "SELECT _utf8mb4 'hola'", "SELECT _utf8mb4 AS [hola]"},
		{"fabric", "SELECT _utf8mb4'a'", "SELECT _utf8mb4 AS [a]"},
		{"fabric", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"fabric", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"fabric", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"fabric", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"fabric", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"fabric", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b AS (a + a) PERSISTED)"},
		{"fabric", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b AS (a * 2))"},
		{"fabric", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b AS (a * 2) NOT NULL)"},
		{"fabric", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b AS ((a * 2)) PERSISTED)"},
		{"fabric", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"fabric", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"fabric", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"fabric", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"fabric", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"presto", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"presto", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"presto", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"presto", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"presto", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"presto", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"presto", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"presto", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INTEGER, b INTEGER AS (a + a) PERSISTED)"},
		{"presto", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INTEGER, b INTEGER AS (a * 2))"},
		{"presto", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INTEGER, b INTEGER AS (a * 2) NOT NULL)"},
		{"presto", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INTEGER, b INTEGER AS ((a * 2)) PERSISTED)"},
		{"presto", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"presto", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"presto", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"presto", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"presto", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"trino", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"trino", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"trino", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"trino", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"trino", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"trino", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"trino", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"trino", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INTEGER, b INTEGER AS (a + a) PERSISTED)"},
		{"trino", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INTEGER, b INTEGER AS (a * 2))"},
		{"trino", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INTEGER, b INTEGER AS (a * 2) NOT NULL)"},
		{"trino", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INTEGER, b INTEGER AS ((a * 2)) PERSISTED)"},
		{"trino", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"trino", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"trino", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"trino", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"trino", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"dremio", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"dremio", "INSERT IGNORE", "INSERT INTO IGNORE"},
		{"dremio", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"dremio", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"dremio", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"dremio", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"dremio", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS VARCHAR)"},
		{"dremio", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT AS (a + a) PERSISTED)"},
		{"dremio", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT AS (a * 2))"},
		{"dremio", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT AS (a * 2) NOT NULL)"},
		{"dremio", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT AS ((a * 2)) PERSISTED)"},
		{"dremio", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"dremio", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"dremio", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"dremio", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"dremio", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
		{"mysql", "INSERT IGNORE INTO foo (x, y) VALUES (1, 2)", "INSERT IGNORE INTO foo (x, y) VALUES (1, 2)"},
		{"mysql", "INSERT IGNORE INTO foo VALUES (1)", "INSERT IGNORE INTO foo VALUES (1)"},
		{"mysql", "INSERT IGNORE INTO foo (a) SELECT 1", "INSERT IGNORE INTO foo (a) SELECT 1"},
		{"mysql", "INSERT IGNORE INTO t (a) VALUES (1) ON DUPLICATE KEY UPDATE a = 1", "INSERT IGNORE INTO t (a) VALUES (1) ON DUPLICATE KEY UPDATE a = 1"},
		{"mysql", "INSERT INTO foo VALUES (1)", "INSERT INTO foo VALUES (1)"},
		{"mysql", "INSERT IGNORE foo VALUES (1)", "INSERT IGNORE INTO foo VALUES (1)"},
		{"mysql", "SELECT _utf8mb4 'hola'", "SELECT _utf8mb4 'hola'"},
		{"mysql", "SELECT _latin1 x'4D79'", "SELECT _latin1 x'4D79'"},
		{"mysql", "SELECT _utf8mb4'a'", "SELECT _utf8mb4 'a'"},
		{"mysql", "SELECT _binary 'a' = b", "SELECT _binary 'a' = b"},
		{"mysql", "SELECT _utf8mb4 1", "SELECT _utf8mb4 1"},
		{"mysql", "SELECT _utf8mb4", "SELECT _utf8mb4"},
		{"mysql", "SELECT CAST(x AS CHAR CHARACTER SET latin1)", "SELECT CAST(x AS CHAR CHARACTER SET latin1)"},
		{"mysql", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')", "SELECT CAST(x AS CHAR CHARACTER SET 'latin1')"},
		{"mysql", "SELECT CAST(x AS CHAR(10) CHARACTER SET utf8)", "SELECT CAST(x AS CHAR CHARACTER SET utf8)"},
		{"mysql", "SELECT CAST(x AS CHAR)", "SELECT CAST(x AS CHAR)"},
		{"mysql", "CREATE TABLE t (a INT, b INT AS (a + a) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a + a) STORED)"},
		{"mysql", "CREATE TABLE t (a INT, b INT AS (a * 2))", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a * 2) VIRTUAL)"},
		{"mysql", "CREATE TABLE t (a INT, b INT AS (a * 2) VIRTUAL NOT NULL)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a * 2) VIRTUAL NOT NULL)"},
		{"mysql", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a * 2) VIRTUAL)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a * 2) VIRTUAL)"},
		{"mysql", "CREATE TABLE t (a INT, b INT AS ((a * 2)) STORED)", "CREATE TABLE t (a INT, b INT GENERATED ALWAYS AS (a * 2) STORED)"},
		{"mysql", "SELECT 'foo' SOUNDS LIKE 'bar'", "SELECT SOUNDEX('foo') = SOUNDEX('bar')"},
		{"mysql", "SELECT a SOUNDS LIKE b IS NULL", "SELECT (SOUNDEX(a) = SOUNDEX(b)) IS NULL"},
		{"mysql", "SELECT a SOUNDS LIKE b | c", "SELECT SOUNDEX(a) = SOUNDEX(b | c)"},
		{"mysql", "SELECT a SOUNDS LIKE b AND c", "SELECT SOUNDEX(a) = SOUNDEX(b) AND c"},
		{"mysql", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)", "SELECT MATCH(a, b) AGAINST('abc' IN BOOLEAN MODE)"},
		{"mysql", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' WITH QUERY EXPANSION)"},
		{"mysql", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)"},
		{"mysql", "SELECT MATCH(a) AGAINST('abc')", "SELECT MATCH(a) AGAINST('abc')"},
		{"mysql", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)", "SELECT MATCH(a) AGAINST('abc' IN NATURAL LANGUAGE MODE)"},
	} {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written < 50 {
		t.Errorf("only %d statements were written back", written)
	}
	for _, sql := range []string{
		"INSERT IGNORE",
		"SELECT _utf8mb4",
		"SELECT CAST(x AS CHAR CHARACTER SET",
		"SELECT CAST(x AS CHAR CHARACTER SET `latin1`)",
		"CREATE TABLE t (a INT, b INT AS (",
		"CREATE TABLE t (a INT, b INT AS a STORED)",
		"SELECT a SOUNDS LIKE",
		"SELECT MATCH(a) AGAINST('x' IN NATURAL LANGUAGE",
	} {
		if tree, err := ParseOne(sql, "mysql"); err == nil && tree != nil {
			_, _ = Generate(tree, "mysql")
		}
	}
	tree, err := ParseOne("SELECT MATCH(a) AGAINST('x' IN BOOLEAN MODE)", "mysql")
	if err != nil {
		t.Fatal(err)
	}
	if out, err := Generate(tree, "postgres"); err == nil {
		t.Errorf("another dialect wrote a MATCH modifier: %s", out)
	}
}
