package sqlglot

import "testing"

// TestMySQLRoundTrips holds the port to what the pinned reference writes for a
// spread of MySQL statements (SHOW, index constraints, UNSIGNED types, the
// restricted CAST vocabulary, GROUP_CONCAT, assignments and the rest). A
// statement the port declines is fine; one it writes differently is not.
func TestMySQLRoundTrips(t *testing.T) {
	cases := [][2]string{
		{"SHOW BINLOG EVENTS FROM 5", "SHOW BINLOG EVENTS FROM 5"},
		{"SHOW RELAYLOG EVENTS FROM 7", "SHOW RELAYLOG EVENTS FROM 7"},
		{"SHOW COLUMNS FROM db.t", "SHOW COLUMNS FROM t FROM db"},
		{"SHOW TABLE STATUS FROM db", "SHOW TABLE STATUS FROM db"},
		{"SHOW OPEN TABLES", "SHOW OPEN TABLES"},
		{"SHOW PLUGINS", "SHOW PLUGINS"},
		{"SHOW ENGINES", "SHOW ENGINES"},
		{"SHOW STORAGE ENGINES", "SHOW ENGINES"},
		{"SHOW EVENTS FROM db", "SHOW EVENTS FROM db"},
		{"SHOW TRIGGERS", "SHOW TRIGGERS"},
		{"SHOW PRIVILEGES", "SHOW PRIVILEGES"},
		{"SHOW WARNINGS LIMIT 5", "SHOW WARNINGS LIMIT 5"},
		{"SHOW ERRORS LIMIT 1, 5", "SHOW ERRORS LIMIT 1, 5"},
		{"SHOW COUNT(*) ERRORS", "SHOW COUNT(*) ERRORS"},
		{"SHOW STATUS WHERE Variable_name = 'x'", "SHOW STATUS WHERE Variable_name = 'x'"},
		{"SHOW FULL PROCESSLIST", "SHOW FULL PROCESSLIST"},
		{"SHOW GLOBAL VARIABLES", "SHOW GLOBAL VARIABLES"},
		{"SHOW SESSION VARIABLES LIKE 'a'", "SHOW VARIABLES LIKE 'a'"},
		{"SHOW CREATE DATABASE db", "SHOW CREATE DATABASE db"},
		{"SHOW CREATE VIEW v", "SHOW CREATE VIEW v"},
		{"SHOW CREATE PROCEDURE p", "SHOW CREATE PROCEDURE p"},
		{"SHOW BINARY LOGS", "SHOW BINARY LOGS"},
		{"SHOW GRANTS", "SHOW GRANTS FOR"},
		{"SHOW REPLICAS", "SHOW REPLICAS"},
		{"SHOW SLAVE HOSTS", "SHOW REPLICAS"},
		{"SHOW REPLICA STATUS", "SHOW REPLICA STATUS"},
		{"SHOW PROCEDURE STATUS LIKE 'x'", "SHOW PROCEDURE STATUS LIKE 'x'"},
		{"SHOW FUNCTION STATUS", "SHOW FUNCTION STATUS"},
		{"SHOW INDEXES FROM t", "SHOW INDEXES FROM t"},
		{"SHOW KEYS FROM t", "SHOW KEYS FROM t"},
		{"SHOW EXTENDED INDEX FROM t", "SHOW EXTENDED INDEX FROM t"},
		{"SHOW SCHEMAS", "SHOW DATABASES"},
		{"SHOW CHARSET", "SHOW CHARACTER SET"},
		{"SELECT GROUP_CONCAT(a SEPARATOR x) FROM t", "SELECT GROUP_CONCAT(a SEPARATOR x) FROM t"},
		{"SELECT GROUP_CONCAT(a ORDER BY b DESC) FROM t", "SELECT GROUP_CONCAT(a ORDER BY b DESC SEPARATOR ',') FROM t"},
		{"SELECT GROUP_CONCAT(DISTINCT a, b) FROM t", "SELECT GROUP_CONCAT(DISTINCT CONCAT(a, b) SEPARATOR ',') FROM t"},
		{"CREATE TABLE t (a INT, PRIMARY KEY pk (a))", "CREATE TABLE t (a INT, PRIMARY KEY pk (a))"},
		{"CREATE TABLE t (a INT, UNIQUE INDEX u (a))", "CREATE TABLE t (a INT, UNIQUE u (a))"},
		{"CREATE TABLE t (a INT, INDEX (a))", "CREATE TABLE t (a INT, INDEX (a))"},
		{"CREATE TABLE t (a INT, INDEX i USING BTREE (a))", "CREATE TABLE t (a INT, INDEX i USING BTREE (a))"},
		{"CREATE TABLE t (a INT GENERATED ALWAYS AS (1 + 2) STORED, b INT GENERATED ALWAYS AS (1) VIRTUAL)", "CREATE TABLE t (a INT GENERATED ALWAYS AS (1 + 2) STORED, b INT GENERATED ALWAYS AS (1) VIRTUAL)"},
		{"CREATE TABLE t (a DOUBLE UNSIGNED, b TINYINT UNSIGNED, c SMALLINT UNSIGNED, d MEDIUMINT UNSIGNED)", "CREATE TABLE t (a DOUBLE UNSIGNED, b TINYINT UNSIGNED, c SMALLINT UNSIGNED, d MEDIUMINT UNSIGNED)"},
		{"SELECT DATE_ADD(x, INTERVAL -1 DAY)", "SELECT DATE_ADD(x, INTERVAL '-1' DAY)"},
		{"SELECT DATE_SUB(x, INTERVAL 1 MONTH)", "SELECT DATE_SUB(x, INTERVAL '1' MONTH)"},
		{"SELECT x MEMBER OF (y)", "SELECT x MEMBER OF(y)"},
		{"SELECT CAST(x AS DATETIME), CAST(x AS DATE), CAST(x AS DECIMAL(10, 2))", "SELECT CAST(x AS DATETIME), CAST(x AS DATE), CAST(x AS DECIMAL(10, 2))"},
		{"SELECT CAST(x AS BIGINT), CAST(x AS TINYINT), CAST(x AS LONGTEXT), CAST(x AS MEDIUMBLOB)", "SELECT CAST(x AS SIGNED), CAST(x AS SIGNED), CAST(x AS CHAR), CAST(x AS CHAR)"},
		{"SELECT @@session.sql_mode", "SELECT @@session.sql_mode"},
		{"SELECT DATE_FORMAT(x, '%M %e'), STR_TO_DATE(x, '%r')", "SELECT DATE_FORMAT(x, '%M %e'), STR_TO_DATE(x, '%r')"},
		{"SELECT TIME_STR_TO_TIME('2023-01-01 13:14:15')", "SELECT CAST('2023-01-01 13:14:15' AS DATETIME)"},
		{"SELECT TIME_STR_TO_TIME('2023-01-01 13:14:15.123456')", "SELECT CAST('2023-01-01 13:14:15.123456' AS DATETIME(6))"},
		{"SELECT CURRENT_DATE AT TIME ZONE 'UTC'", "SELECT CURRENT_DATE"},
		{"SELECT '\\\\', 'a\\nb'", "SELECT '\\\\', 'a\\nb'"},
		{"SELECT JSON_EXTRACT(x, '$.a')", "SELECT JSON_EXTRACT(x, '$.a')"},
		{"SELECT JSON_UNQUOTE(JSON_EXTRACT(x, '$.a', '$.b'))", "SELECT JSON_UNQUOTE(JSON_EXTRACT(x, '$.a', '$.b'))"},
		{"SHOW FULL COLUMNS FROM t FROM db LIKE 'a%'", "SHOW FULL COLUMNS FROM t FROM db LIKE 'a%'"},
		{"SHOW INDEX FROM t", "SHOW INDEX FROM t"},
		{"SHOW GRANTS FOR foo", "SHOW GRANTS FOR foo"},
		{"SHOW ENGINE foo MUTEX", "SHOW ENGINE foo MUTEX"},
		{"SHOW ENGINE foo STATUS", "SHOW ENGINE foo STATUS"},
		{"SHOW BINLOG EVENTS IN 'log' FROM 5 LIMIT 2, 3", "SHOW BINLOG EVENTS IN 'log' FROM 5 LIMIT 2, 3"},
		{"SHOW TABLES FROM db WHERE Name = 'x'", "SHOW TABLES FROM db WHERE Name = 'x'"},
		{"SHOW PROFILE", "SHOW PROFILE"},
		{"SHOW GLOBAL STATUS LIKE 'x%'", "SHOW GLOBAL STATUS LIKE 'x%'"},
		{"SHOW CREATE TABLE t", "SHOW CREATE TABLE t"},
		{"SHOW COLLATION", "SHOW COLLATION"},
		{"SHOW CHARACTER SET", "SHOW CHARACTER SET"},
		{"SHOW DATABASES", "SHOW DATABASES"},
		{"SHOW PROCESSLIST", "SHOW PROCESSLIST"},
		{"SHOW VARIABLES LIKE 'x'", "SHOW VARIABLES LIKE 'x'"},
		{"SHOW MASTER STATUS", "SHOW MASTER STATUS"},
		{"SHOW SLAVE STATUS FOR CHANNEL c1", "SHOW REPLICA STATUS FOR CHANNEL c1"},
		{"CREATE TABLE t (a INT, KEY k (a))", "CREATE TABLE t (a INT, INDEX k (a))"},
		{"CREATE TABLE t (a INT, UNIQUE KEY u (a) USING BTREE)", "CREATE TABLE t (a INT, UNIQUE u (a) USING BTREE)"},
		{"CREATE TABLE t (a INT, FULLTEXT INDEX f (a))", "CREATE TABLE t (a INT, FULLTEXT INDEX f (a))"},
		{"CREATE TABLE t (a INT, SPATIAL KEY s (a))", "CREATE TABLE t (a INT, SPATIAL INDEX s (a))"},
		{"CREATE TABLE t (a INT, PRIMARY KEY (a) USING HASH)", "CREATE TABLE t (a INT, PRIMARY KEY (a) USING HASH)"},
		{"CREATE TABLE t (a INT KEY)", "CREATE TABLE t (a INT PRIMARY KEY)"},
		{"CREATE TABLE t (a BIGINT UNSIGNED, b INT UNSIGNED, c DECIMAL(10, 2) UNSIGNED)", "CREATE TABLE t (a BIGINT UNSIGNED, b INT UNSIGNED, c DECIMAL(10, 2) UNSIGNED)"},
		{"ALTER TABLE t MODIFY COLUMN a INT NOT NULL", "ALTER TABLE t MODIFY COLUMN a INT NOT NULL"},
		{"ALTER TABLE t CHANGE COLUMN a b INT", "ALTER TABLE t CHANGE COLUMN a b INT"},
		{"ALTER TABLE t ALTER COLUMN a SET DATA TYPE INT NOT NULL", "ALTER TABLE t ALTER COLUMN a SET DATA TYPE INT NOT NULL"},
		{"SELECT CAST(a AS SIGNED), CAST(b AS UNSIGNED), CAST(c AS CHAR), CAST(d AS TIMESTAMP)", "SELECT CAST(a AS SIGNED), CAST(b AS UNSIGNED), CAST(c AS CHAR), TIMESTAMP(d)"},
		{"SELECT CAST(a AS TEXT), CAST(b AS BOOLEAN)", "SELECT CAST(a AS CHAR), CAST(b AS SIGNED)"},
		{"SELECT GROUP_CONCAT(DISTINCT a ORDER BY a SEPARATOR ';') FROM t", "SELECT GROUP_CONCAT(DISTINCT a ORDER BY a SEPARATOR ';') FROM t"},
		{"SELECT GROUP_CONCAT(a, b) FROM t", "SELECT GROUP_CONCAT(CONCAT(a, b) SEPARATOR ',') FROM t"},
		{"SELECT STR_TO_DATE(x, '%Y-%m-%d'), STR_TO_DATE(x, '%T')", "SELECT STR_TO_DATE(x, '%Y-%m-%d'), STR_TO_DATE(x, '%T')"},
		{"SELECT DATE_ADD(x, INTERVAL 1 DAY), DATE_SUB(x, INTERVAL 2 * 3 DAY)", "SELECT DATE_ADD(x, INTERVAL '1' DAY), DATE_SUB(x, INTERVAL (2 * 3) DAY)"},
		{"SELECT @@global.x, @@y", "SELECT @@global.x, @@y"},
		{"SELECT @a := 1, @b := @a + 1", "SELECT @a := 1, @b := @a + 1"},
		{"SELECT 1 MEMBER OF('[1]')", "SELECT 1 MEMBER OF('[1]')"},
		{"SET PERSIST a = 1", "SET PERSIST a = 1"},
		{"SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED, READ ONLY", "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED, READ ONLY"},
		{"SET TRANSACTION READ WRITE", "SET TRANSACTION READ WRITE"},
		{"SET NAMES utf8", "SET NAMES utf8"},
		{"SET CHARACTER SET utf8", "SET CHARACTER SET utf8"},
		{"SELECT DATE_FORMAT(x, '%Y %T')", "SELECT DATE_FORMAT(x, '%Y %T')"},
		{"SELECT TIME_STR_TO_TIME('2023-01-01 13:14:15.123+00:00')", "SELECT CAST('2023-01-01 13:14:15.123+00:00' AS DATETIME(3))"},
		{"SELECT x AT TIME ZONE 'UTC'", "SELECT x"},
		{"SELECT 'a\\tb', 'it''s'", "SELECT 'a\\tb', 'it''s'"},
		{"SELECT JSON_EXTRACT(x, '$.a', '$.b')", "SELECT JSON_EXTRACT(x, '$.a', '$.b')"},
		{"SELECT * FROM t WHERE a = 1 UNION ALL SELECT * FROM u", "SELECT * FROM t WHERE a = 1 UNION ALL SELECT * FROM u"},
		{"SELECT CHAR(65 USING utf8)", "SELECT CHAR(65 USING utf8)"},
	}
	written := 0
	for _, c := range cases {
		tree, err := ParseOne(c[0], "mysql")
		if err != nil {
			continue
		}
		got, err := Generate(tree, "mysql")
		if err != nil {
			continue
		}
		written++
		if got != c[1] {
			t.Errorf("%s\n  want %s\n  got  %s", c[0], c[1], got)
		}
	}
	if written < len(cases)*3/4 {
		t.Errorf("only %d of %d statements were written at all", written, len(cases))
	}
}

// TestMySQLDeclines walks the malformed and out-of-scope shapes of the MySQL
// statements the port reads: each must be turned away cleanly, never panic and
// never come back as a tree of the wrong shape.
func TestMySQLDeclines(t *testing.T) {
	for _, sql := range []string{
		"SHOW COLUMNS FROM",
		"SHOW TABLES FROM",
		"SHOW TABLES FROM a.",
		"SHOW TABLES IN",
		"SHOW BINLOG EVENTS IN 'log' FROM 5 LIMIT 2, 3",
		"SHOW BINLOG EVENTS FROM x",
		"SHOW SLAVE STATUS FOR CHANNEL",
		"SHOW TABLES LIKE",
		"SHOW WARNINGS LIMIT",
		"SHOW WARNINGS LIMIT 1,",
		"SHOW PROFILE CPU",
		"SHOW PROFILE FOR QUERY 1",
		"SHOW PROFILE OFFSET 1",
		"SHOW PROFILE LIMIT 1",
		"SHOW TABLES FOR TABLE",
		"SHOW TABLES FOR TABLE t",
		"SHOW TABLES FOR GROUP 'g'",
		"SHOW TABLES FOR USER 'u'",
		"SHOW TABLES FOR ROLE 'r'",
		"SHOW TABLES INTO OUTFILE 'f'",
		"SHOW TABLES garbage",
		"SHOW ENGINE",
		"SHOW ENGINE INNODB",
		"SHOW ENGINE INNODB MUTEX",
		"SHOW JSON TABLES",
		"CREATE TABLE t (a INT, KEY)",
		"CREATE TABLE t (a INT, KEY k)",
		"CREATE TABLE t (a INT, KEY k (a",
		"CREATE TABLE t (a INT, FULLTEXT)",
		"CREATE TABLE t (a INT, PRIMARY KEY pk)",
		"CREATE TABLE t (a INT, UNIQUE KEY)",
		"CREATE TABLE t (a INT, INDEX USING)",
		"CREATE TABLE t (a FLOAT UNSIGNED)",
		"CREATE TABLE t (a VARCHAR(3) UNSIGNED)",
		"ALTER TABLE t MODIFY",
		"ALTER TABLE t CHANGE a",
		"ALTER TABLE t MODIFY COLUMN a",
		"SET GLOBAL TRANSACTION",
		"SET TRANSACTION ISOLATION LEVEL",
		"SET NAMES",
		"SET CHARACTER SET",
		"SET PERSIST",
		"SELECT @@",
		"SELECT @@a.",
		"SELECT 1 MEMBER OF",
		"SELECT 1 MEMBER OF 2",
		"SELECT GROUP_CONCAT(a SEPARATOR) FROM t",
		"SELECT GROUP_CONCAT(a ORDER) FROM t",
		"SELECT GROUP_CONCAT() FROM t",
		"SELECT STR_TO_DATE(x) ",
		"SELECT DATE_ADD(x)",
		"SELECT DATE_ADD(x, INTERVAL 1)",
		"SELECT @a :=",
		"SELECT CHAR(65 USING)",
	} {
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Errorf("%s: panicked: %v", sql, r)
				}
			}()
			if tree, err := ParseOne(sql, "mysql"); err == nil && tree != nil {
				_, _ = Generate(tree, "mysql")
			}
		}()
	}
}
