package sqlglot

import "testing"

// TestTrinoRoutines holds the port to what the pinned reference writes for
// Trino's inline SQL routines: every control-flow statement, labels,
// characteristics and a WITH clause mixing routines and CTEs.
func TestTrinoRoutines(t *testing.T) {
	for _, c := range [][2]string{
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN IF x > 1 THEN RETURN 1; ELSEIF x > 0 THEN RETURN 2; ELSE RETURN 3; END IF; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN IF x > 1 THEN RETURN 1; ELSEIF x > 0 THEN RETURN 2; ELSE RETURN 3; END IF; END SELECT F(1)"},
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN CASE x WHEN 1 THEN RETURN 1; WHEN 2 THEN RETURN 2; ELSE RETURN 3; END CASE; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN CASE x WHEN 1 THEN RETURN 1; WHEN 2 THEN RETURN 2; ELSE RETURN 3; END CASE; END SELECT F(1)"},
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN CASE WHEN x > 1 THEN RETURN 1; END CASE; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN CASE WHEN x > 1 THEN RETURN 1; END CASE; END SELECT F(1)"},
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; WHILE i < x DO SET i = i + 1; END WHILE; RETURN i; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; WHILE i < x DO SET i = i + 1; END WHILE; RETURN i; END SELECT F(1)"},
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; w: WHILE i < x DO SET i = i + 1; ITERATE w; END WHILE; RETURN i; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; w: WHILE i < x DO SET i = i + 1; ITERATE w; END WHILE; RETURN i; END SELECT F(1)"},
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; REPEAT SET i = i + 1; UNTIL i >= x END REPEAT; RETURN i; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; REPEAT SET i = i + 1; UNTIL i >= x END REPEAT; RETURN i; END SELECT F(1)"},
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; r: REPEAT SET i = i + 1; UNTIL i >= x END REPEAT; RETURN i; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN DECLARE i INTEGER DEFAULT 0; r: REPEAT SET i = i + 1; UNTIL i >= x END REPEAT; RETURN i; END SELECT F(1)"},
		{"WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN l: LOOP LEAVE l; END LOOP; RETURN 1; END SELECT f(1)", "WITH FUNCTION f(x INTEGER) RETURNS INTEGER BEGIN l: LOOP LEAVE l; END LOOP; RETURN 1; END SELECT F(1)"},
		{"WITH FUNCTION f() RETURNS INTEGER COMMENT 'hi' SECURITY DEFINER NOT DETERMINISTIC WITH (a=1) RETURN 1, FUNCTION g() RETURNS INTEGER RETURN 2 WITH RECURSIVE t(n) AS (SELECT 1) SELECT f() FROM t", "WITH FUNCTION f() RETURNS INTEGER COMMENT 'hi' SECURITY DEFINER NOT DETERMINISTIC WITH (a=1) RETURN 1, FUNCTION g() RETURNS INTEGER RETURN 2 WITH RECURSIVE t(n) AS (SELECT 1) SELECT F() FROM t"},
		{"WITH function AS (SELECT 1) SELECT * FROM function", "WITH function AS (SELECT 1) SELECT * FROM function"},
	} {
		tree, err := ParseOne(c[0], "trino")
		if err != nil {
			t.Errorf("%s: %v", c[0], err)
			continue
		}
		got, err := Generate(tree, "trino")
		if err != nil {
			t.Errorf("%s: %v", c[0], err)
			continue
		}
		if got != c[1] {
			t.Errorf("%s\n  want %s\n  got  %s", c[0], c[1], got)
		}
	}
}

// TestTrinoRoutineDeclines walks the malformed shapes: each is turned away
// cleanly, and the routine statements are refused by every other dialect.
func TestTrinoRoutineDeclines(t *testing.T) {
	for _, sql := range []string{
		"WITH FUNCTION f() RETURNS INTEGER",
		"WITH FUNCTION f() RETURNS INTEGER RETURN",
		"WITH FUNCTION f() RETURNS INTEGER SECURITY RETURN 1 SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER SECURITY WHATEVER RETURN 1 SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER COMMENT RETURN 1 SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER WITH a=1 RETURN 1 SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER WITH (a=1 RETURN 1 SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN RETURN 1;",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN SELECT 1; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN 1: LOOP END LOOP; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN LEAVE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN ITERATE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN LEAVE 'x'; END SELECT 1",
		"WITH FUNCTION (",
		"WITH FUNCTION f(",
		"WITH FUNCTION f() WITH (=) RETURN 1 SELECT 1",
		"WITH FUNCTION f() RETURNS RETURN 1 SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER RETURN )",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN RETURN ); END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN IF ) THEN RETURN 1; END IF; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN IF 1 THEN RETURN ); END IF; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN IF 1 THEN RETURN 1; ELSEIF ) THEN RETURN 2; END IF; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN IF 1 THEN RETURN 1; ELSE RETURN ); END IF; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN CASE ) WHEN 1 THEN RETURN 1; END CASE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN CASE x WHEN ) THEN RETURN 1; END CASE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN CASE x WHEN 1 THEN RETURN 1; ELSE RETURN ); END CASE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN WHILE ) DO RETURN 1; END WHILE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN WHILE 1 DO RETURN ); END WHILE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN LOOP RETURN ); END LOOP; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN REPEAT RETURN ); UNTIL 1 END REPEAT; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN REPEAT RETURN 1; UNTIL ) END REPEAT; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN REPEAT RETURN 1; UNTIL 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN DECLARE ; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN SET ; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN BEGIN RETURN ); END; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN x: END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN x:",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN LOOP END LOOP;",
	} {
		if tree, err := ParseOne(sql, "trino"); err == nil && tree != nil {
			_, _ = Generate(tree, "trino")
		}
	}
	tree, err := ParseOne("WITH FUNCTION f() RETURNS INTEGER BEGIN IF 1 = 1 THEN RETURN 1; END IF; END SELECT 1", "trino")
	if err != nil {
		t.Fatal(err)
	}
	for _, dialect := range []string{"presto", "postgres", "mysql", "tsql", "duckdb"} {
		if out, err := Generate(tree, dialect); err == nil {
			t.Errorf("%s wrote a Trino routine: %s", dialect, out)
		}
	}
	for _, sql := range []string{
		"WITH FUNCTION f() RETURNS INTEGER BEGIN CASE x WHEN 1 THEN RETURN 1; END CASE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN WHILE 1 DO RETURN 1; END WHILE; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN LOOP LEAVE l; END LOOP; END SELECT 1",
		"WITH FUNCTION f() RETURNS INTEGER BEGIN REPEAT ITERATE l; UNTIL 1 END REPEAT; END SELECT 1",
	} {
		tree, err := ParseOne(sql, "trino")
		if err != nil {
			t.Fatal(err)
		}
		for _, dialect := range []string{"presto", "postgres", "mysql"} {
			if out, err := Generate(tree, dialect); err == nil {
				t.Errorf("%s wrote a Trino routine statement: %s", dialect, out)
			}
		}
	}
}
