// Code generated by harness/gen_tokenizer.py from the pinned reference. DO NOT EDIT.
//
// The token types the reference defines, with the reference's own ordinals so
// a generated table and a hand-written switch cannot drift apart silently.

package sqlglot

// TokenType identifies a lexical token. Values match the reference's IntEnum.
type TokenType int

const (
	TokL_PAREN                 TokenType = 1
	TokR_PAREN                 TokenType = 2
	TokL_BRACKET               TokenType = 3
	TokR_BRACKET               TokenType = 4
	TokL_BRACE                 TokenType = 5
	TokR_BRACE                 TokenType = 6
	TokCOMMA                   TokenType = 7
	TokDOT                     TokenType = 8
	TokDASH                    TokenType = 9
	TokPLUS                    TokenType = 10
	TokCOLON                   TokenType = 11
	TokDOTCOLON                TokenType = 12
	TokDOTCARET                TokenType = 13
	TokDCOLON                  TokenType = 14
	TokDCOLONDOLLAR            TokenType = 15
	TokDCOLONPERCENT           TokenType = 16
	TokDCOLONQMARK             TokenType = 17
	TokDQMARK                  TokenType = 18
	TokSEMICOLON               TokenType = 19
	TokSTAR                    TokenType = 20
	TokBACKSLASH               TokenType = 21
	TokSLASH                   TokenType = 22
	TokLT                      TokenType = 23
	TokLTE                     TokenType = 24
	TokGT                      TokenType = 25
	TokGTE                     TokenType = 26
	TokNOT                     TokenType = 27
	TokEQ                      TokenType = 28
	TokNEQ                     TokenType = 29
	TokNULLSAFE_EQ             TokenType = 30
	TokCOLON_EQ                TokenType = 31
	TokCOLON_GT                TokenType = 32
	TokNCOLON_GT               TokenType = 33
	TokAND                     TokenType = 34
	TokOR                      TokenType = 35
	TokAMP                     TokenType = 36
	TokDPIPE                   TokenType = 37
	TokPIPE_GT                 TokenType = 38
	TokPIPE                    TokenType = 39
	TokPIPE_SLASH              TokenType = 40
	TokDPIPE_SLASH             TokenType = 41
	TokCARET                   TokenType = 42
	TokCARET_AT                TokenType = 43
	TokTILDE                   TokenType = 44
	TokARROW                   TokenType = 45
	TokDARROW                  TokenType = 46
	TokFARROW                  TokenType = 47
	TokHASH                    TokenType = 48
	TokHASH_ARROW              TokenType = 49
	TokDHASH_ARROW             TokenType = 50
	TokLR_ARROW                TokenType = 51
	TokLLRR_ARROW              TokenType = 52
	TokDAT                     TokenType = 53
	TokAT_QMARK                TokenType = 54
	TokLT_AT                   TokenType = 55
	TokAT_GT                   TokenType = 56
	TokDOLLAR                  TokenType = 57
	TokPARAMETER               TokenType = 58
	TokSESSION                 TokenType = 59
	TokSESSION_PARAMETER       TokenType = 60
	TokSESSION_USER            TokenType = 61
	TokDAMP                    TokenType = 62
	TokAMP_LT                  TokenType = 63
	TokAMP_GT                  TokenType = 64
	TokADJACENT                TokenType = 65
	TokXOR                     TokenType = 66
	TokDSTAR                   TokenType = 67
	TokQMARK_AMP               TokenType = 68
	TokQMARK_PIPE              TokenType = 69
	TokHASH_DASH               TokenType = 70
	TokEXCLAMATION             TokenType = 71
	TokURI_START               TokenType = 72
	TokBLOCK_START             TokenType = 73
	TokBLOCK_END               TokenType = 74
	TokSPACE                   TokenType = 75
	TokBREAK                   TokenType = 76
	TokSTRING                  TokenType = 77
	TokNUMBER                  TokenType = 78
	TokIDENTIFIER              TokenType = 79
	TokDATABASE                TokenType = 80
	TokCOLUMN                  TokenType = 81
	TokCOLUMN_DEF              TokenType = 82
	TokSCHEMA                  TokenType = 83
	TokTABLE                   TokenType = 84
	TokWAREHOUSE               TokenType = 85
	TokSTAGE                   TokenType = 86
	TokSTREAM                  TokenType = 87
	TokSTREAMLIT               TokenType = 88
	TokVAR                     TokenType = 89
	TokBIT_STRING              TokenType = 90
	TokHEX_STRING              TokenType = 91
	TokBYTE_STRING             TokenType = 92
	TokNATIONAL_STRING         TokenType = 93
	TokRAW_STRING              TokenType = 94
	TokHEREDOC_STRING          TokenType = 95
	TokUNICODE_STRING          TokenType = 96
	TokBIT                     TokenType = 97
	TokBOOLEAN                 TokenType = 98
	TokTINYINT                 TokenType = 99
	TokUTINYINT                TokenType = 100
	TokSMALLINT                TokenType = 101
	TokUSMALLINT               TokenType = 102
	TokMEDIUMINT               TokenType = 103
	TokUMEDIUMINT              TokenType = 104
	TokINT                     TokenType = 105
	TokUINT                    TokenType = 106
	TokBIGINT                  TokenType = 107
	TokUBIGINT                 TokenType = 108
	TokBIGNUM                  TokenType = 109
	TokINT128                  TokenType = 110
	TokUINT128                 TokenType = 111
	TokINT256                  TokenType = 112
	TokUINT256                 TokenType = 113
	TokFLOAT                   TokenType = 114
	TokDOUBLE                  TokenType = 115
	TokUDOUBLE                 TokenType = 116
	TokDECIMAL                 TokenType = 117
	TokDECIMAL32               TokenType = 118
	TokDECIMAL64               TokenType = 119
	TokDECIMAL128              TokenType = 120
	TokDECIMAL256              TokenType = 121
	TokDECFLOAT                TokenType = 122
	TokUDECIMAL                TokenType = 123
	TokBIGDECIMAL              TokenType = 124
	TokCHAR                    TokenType = 125
	TokNCHAR                   TokenType = 126
	TokVARCHAR                 TokenType = 127
	TokNVARCHAR                TokenType = 128
	TokBPCHAR                  TokenType = 129
	TokTEXT                    TokenType = 130
	TokMEDIUMTEXT              TokenType = 131
	TokLONGTEXT                TokenType = 132
	TokBLOB                    TokenType = 133
	TokMEDIUMBLOB              TokenType = 134
	TokLONGBLOB                TokenType = 135
	TokTINYBLOB                TokenType = 136
	TokTINYTEXT                TokenType = 137
	TokNAME                    TokenType = 138
	TokBINARY                  TokenType = 139
	TokVARBINARY               TokenType = 140
	TokJSON                    TokenType = 141
	TokJSONB                   TokenType = 142
	TokTIME                    TokenType = 143
	TokTIMETZ                  TokenType = 144
	TokTIME_NS                 TokenType = 145
	TokTIMESTAMP               TokenType = 146
	TokTIMESTAMPTZ             TokenType = 147
	TokTIMESTAMPLTZ            TokenType = 148
	TokTIMESTAMPNTZ            TokenType = 149
	TokTIMESTAMP_S             TokenType = 150
	TokTIMESTAMP_MS            TokenType = 151
	TokTIMESTAMP_NS            TokenType = 152
	TokDATETIME                TokenType = 153
	TokDATETIME2               TokenType = 154
	TokDATETIME64              TokenType = 155
	TokSMALLDATETIME           TokenType = 156
	TokDATE                    TokenType = 157
	TokDATE32                  TokenType = 158
	TokINT4RANGE               TokenType = 159
	TokINT4MULTIRANGE          TokenType = 160
	TokINT8RANGE               TokenType = 161
	TokINT8MULTIRANGE          TokenType = 162
	TokNUMRANGE                TokenType = 163
	TokNUMMULTIRANGE           TokenType = 164
	TokTSRANGE                 TokenType = 165
	TokTSMULTIRANGE            TokenType = 166
	TokTSTZRANGE               TokenType = 167
	TokTSTZMULTIRANGE          TokenType = 168
	TokDATERANGE               TokenType = 169
	TokDATEMULTIRANGE          TokenType = 170
	TokUUID                    TokenType = 171
	TokGEOGRAPHY               TokenType = 172
	TokGEOGRAPHYPOINT          TokenType = 173
	TokNULLABLE                TokenType = 174
	TokGEOMETRY                TokenType = 175
	TokPOINT                   TokenType = 176
	TokRING                    TokenType = 177
	TokLINESTRING              TokenType = 178
	TokLOCALTIME               TokenType = 179
	TokLOCALTIMESTAMP          TokenType = 180
	TokSYSTIMESTAMP            TokenType = 181
	TokMULTILINESTRING         TokenType = 182
	TokPOLYGON                 TokenType = 183
	TokMULTIPOLYGON            TokenType = 184
	TokHLLSKETCH               TokenType = 185
	TokHSTORE                  TokenType = 186
	TokSUPER                   TokenType = 187
	TokSERIAL                  TokenType = 188
	TokSMALLSERIAL             TokenType = 189
	TokBIGSERIAL               TokenType = 190
	TokXML                     TokenType = 191
	TokYEAR                    TokenType = 192
	TokUSERDEFINED             TokenType = 193
	TokMONEY                   TokenType = 194
	TokSMALLMONEY              TokenType = 195
	TokROWVERSION              TokenType = 196
	TokIMAGE                   TokenType = 197
	TokVARIANT                 TokenType = 198
	TokOBJECT                  TokenType = 199
	TokINET                    TokenType = 200
	TokIPADDRESS               TokenType = 201
	TokIPPREFIX                TokenType = 202
	TokIPV4                    TokenType = 203
	TokIPV6                    TokenType = 204
	TokENUM                    TokenType = 205
	TokENUM8                   TokenType = 206
	TokENUM16                  TokenType = 207
	TokFIXEDSTRING             TokenType = 208
	TokLOWCARDINALITY          TokenType = 209
	TokNESTED                  TokenType = 210
	TokAGGREGATEFUNCTION       TokenType = 211
	TokSIMPLEAGGREGATEFUNCTION TokenType = 212
	TokTDIGEST                 TokenType = 213
	TokUNKNOWN                 TokenType = 214
	TokVECTOR                  TokenType = 215
	TokDYNAMIC                 TokenType = 216
	TokVOID                    TokenType = 217
	TokALIAS                   TokenType = 218
	TokALTER                   TokenType = 219
	TokALL                     TokenType = 220
	TokANTI                    TokenType = 221
	TokANY                     TokenType = 222
	TokAPPLY                   TokenType = 223
	TokARRAY                   TokenType = 224
	TokASC                     TokenType = 225
	TokASOF                    TokenType = 226
	TokATTACH                  TokenType = 227
	TokAUTO_INCREMENT          TokenType = 228
	TokBEGIN                   TokenType = 229
	TokBETWEEN                 TokenType = 230
	TokBULK_COLLECT_INTO       TokenType = 231
	TokCACHE                   TokenType = 232
	TokCASE                    TokenType = 233
	TokCHARACTER_SET           TokenType = 234
	TokCLUSTER_BY              TokenType = 235
	TokCOLLATE                 TokenType = 236
	TokCOMMAND                 TokenType = 237
	TokCOMMENT                 TokenType = 238
	TokCOMMIT                  TokenType = 239
	TokCONNECT_BY              TokenType = 240
	TokCONSTRAINT              TokenType = 241
	TokCOPY                    TokenType = 242
	TokCREATE                  TokenType = 243
	TokCROSS                   TokenType = 244
	TokCUBE                    TokenType = 245
	TokCURRENT_DATE            TokenType = 246
	TokCURRENT_DATETIME        TokenType = 247
	TokCURRENT_SCHEMA          TokenType = 248
	TokCURRENT_TIME            TokenType = 249
	TokCURRENT_TIMESTAMP       TokenType = 250
	TokCURRENT_USER            TokenType = 251
	TokCURRENT_USER_ID         TokenType = 252
	TokCURRENT_ROLE            TokenType = 253
	TokCURRENT_CATALOG         TokenType = 254
	TokDECLARE                 TokenType = 255
	TokDEFAULT                 TokenType = 256
	TokDELETE                  TokenType = 257
	TokDESC                    TokenType = 258
	TokDESCRIBE                TokenType = 259
	TokDETACH                  TokenType = 260
	TokDICTIONARY              TokenType = 261
	TokDISTINCT                TokenType = 262
	TokDISTRIBUTE_BY           TokenType = 263
	TokDIV                     TokenType = 264
	TokDROP                    TokenType = 265
	TokELSE                    TokenType = 266
	TokEND                     TokenType = 267
	TokESCAPE                  TokenType = 268
	TokEXCEPT                  TokenType = 269
	TokEXECUTE                 TokenType = 270
	TokEXISTS                  TokenType = 271
	TokFALSE                   TokenType = 272
	TokFETCH                   TokenType = 273
	TokFILE                    TokenType = 274
	TokFILE_FORMAT             TokenType = 275
	TokFILTER                  TokenType = 276
	TokFINAL                   TokenType = 277
	TokFIRST                   TokenType = 278
	TokFOR                     TokenType = 279
	TokFORCE                   TokenType = 280
	TokFOREIGN_KEY             TokenType = 281
	TokFORMAT                  TokenType = 282
	TokFROM                    TokenType = 283
	TokFULL                    TokenType = 284
	TokFUNCTION                TokenType = 285
	TokGET                     TokenType = 286
	TokGLOB                    TokenType = 287
	TokGLOBAL                  TokenType = 288
	TokGRANT                   TokenType = 289
	TokGROUP_BY                TokenType = 290
	TokGROUPING_SETS           TokenType = 291
	TokHAVING                  TokenType = 292
	TokHINT                    TokenType = 293
	TokIGNORE                  TokenType = 294
	TokILIKE                   TokenType = 295
	TokIN                      TokenType = 296
	TokINDEX                   TokenType = 297
	TokINDEXED_BY              TokenType = 298
	TokINNER                   TokenType = 299
	TokINSERT                  TokenType = 300
	TokINSTALL                 TokenType = 301
	TokINTEGRATION             TokenType = 302
	TokINTERSECT               TokenType = 303
	TokINTERVAL                TokenType = 304
	TokINTO                    TokenType = 305
	TokINTRODUCER              TokenType = 306
	TokIRLIKE                  TokenType = 307
	TokIS                      TokenType = 308
	TokISNULL                  TokenType = 309
	TokJOIN                    TokenType = 310
	TokJOIN_MARKER             TokenType = 311
	TokKEEP                    TokenType = 312
	TokKEY                     TokenType = 313
	TokKILL                    TokenType = 314
	TokLANGUAGE                TokenType = 315
	TokLATERAL                 TokenType = 316
	TokLEFT                    TokenType = 317
	TokLIKE                    TokenType = 318
	TokLIMIT                   TokenType = 319
	TokLIST                    TokenType = 320
	TokLOAD                    TokenType = 321
	TokLOCK                    TokenType = 322
	TokMAP                     TokenType = 323
	TokMATCH                   TokenType = 324
	TokMATCH_CONDITION         TokenType = 325
	TokMATCH_RECOGNIZE         TokenType = 326
	TokMEMBER_OF               TokenType = 327
	TokMERGE                   TokenType = 328
	TokMOD                     TokenType = 329
	TokMODEL                   TokenType = 330
	TokNATURAL                 TokenType = 331
	TokNEXT                    TokenType = 332
	TokNOTHING                 TokenType = 333
	TokNOTNULL                 TokenType = 334
	TokNULL                    TokenType = 335
	TokOBJECT_IDENTIFIER       TokenType = 336
	TokOFFSET                  TokenType = 337
	TokON                      TokenType = 338
	TokONLY                    TokenType = 339
	TokOPERATOR                TokenType = 340
	TokORDER_BY                TokenType = 341
	TokORDER_SIBLINGS_BY       TokenType = 342
	TokORDERED                 TokenType = 343
	TokORDINALITY              TokenType = 344
	TokOUT                     TokenType = 345
	TokINOUT                   TokenType = 346
	TokOUTER                   TokenType = 347
	TokOVER                    TokenType = 348
	TokOVERLAPS                TokenType = 349
	TokOVERWRITE               TokenType = 350
	TokPACKAGE                 TokenType = 351
	TokPARTITION               TokenType = 352
	TokPARTITION_BY            TokenType = 353
	TokPERCENT                 TokenType = 354
	TokPIVOT                   TokenType = 355
	TokPLACEHOLDER             TokenType = 356
	TokPOLICY                  TokenType = 357
	TokPOOL                    TokenType = 358
	TokPOSITIONAL              TokenType = 359
	TokPRAGMA                  TokenType = 360
	TokPREWHERE                TokenType = 361
	TokPRIMARY_KEY             TokenType = 362
	TokPROCEDURE               TokenType = 363
	TokPROPERTIES              TokenType = 364
	TokPROJECTION              TokenType = 365
	TokPSEUDO_TYPE             TokenType = 366
	TokPUT                     TokenType = 367
	TokQUALIFY                 TokenType = 368
	TokQUOTE                   TokenType = 369
	TokQDCOLON                 TokenType = 370
	TokRANGE                   TokenType = 371
	TokRECURSIVE               TokenType = 372
	TokREFRESH                 TokenType = 373
	TokRENAME                  TokenType = 374
	TokREPLACE                 TokenType = 375
	TokRETURNING               TokenType = 376
	TokREVOKE                  TokenType = 377
	TokREFERENCES              TokenType = 378
	TokRIGHT                   TokenType = 379
	TokRLIKE                   TokenType = 380
	TokROLE                    TokenType = 381
	TokROLLBACK                TokenType = 382
	TokROLLUP                  TokenType = 383
	TokROW                     TokenType = 384
	TokROWS                    TokenType = 385
	TokRULE                    TokenType = 386
	TokSELECT                  TokenType = 387
	TokSEMI                    TokenType = 388
	TokSEPARATOR               TokenType = 389
	TokSEQUENCE                TokenType = 390
	TokSERDE_PROPERTIES        TokenType = 391
	TokSET                     TokenType = 392
	TokSETTINGS                TokenType = 393
	TokSHOW                    TokenType = 394
	TokSIMILAR_TO              TokenType = 395
	TokSOME                    TokenType = 396
	TokSORT_BY                 TokenType = 397
	TokSOUNDS_LIKE             TokenType = 398
	TokSQL_SECURITY            TokenType = 399
	TokSTART_WITH              TokenType = 400
	TokSTORAGE_INTEGRATION     TokenType = 401
	TokSTRAIGHT_JOIN           TokenType = 402
	TokSTRUCT                  TokenType = 403
	TokSUMMARIZE               TokenType = 404
	TokTABLE_SAMPLE            TokenType = 405
	TokTAG                     TokenType = 406
	TokTEMPORARY               TokenType = 407
	TokTOP                     TokenType = 408
	TokTHEN                    TokenType = 409
	TokTRUE                    TokenType = 410
	TokTRUNCATE                TokenType = 411
	TokTRIGGER                 TokenType = 412
	TokTYPE                    TokenType = 413
	TokUNCACHE                 TokenType = 414
	TokUNDROP                  TokenType = 415
	TokUNION                   TokenType = 416
	TokUNNEST                  TokenType = 417
	TokUNPIVOT                 TokenType = 418
	TokUPDATE                  TokenType = 419
	TokUSE                     TokenType = 420
	TokUSING                   TokenType = 421
	TokVALUES                  TokenType = 422
	TokVARIADIC                TokenType = 423
	TokVIEW                    TokenType = 424
	TokSEMANTIC_VIEW           TokenType = 425
	TokVOLATILE                TokenType = 426
	TokVOLUME                  TokenType = 427
	TokWHEN                    TokenType = 428
	TokWHERE                   TokenType = 429
	TokWINDOW                  TokenType = 430
	TokWITH                    TokenType = 431
	TokUNIQUE                  TokenType = 432
	TokUTC_DATE                TokenType = 433
	TokUTC_TIME                TokenType = 434
	TokUTC_TIMESTAMP           TokenType = 435
	TokOPTION                  TokenType = 436
	TokSINK                    TokenType = 437
	TokSOURCE                  TokenType = 438
	TokANALYZE                 TokenType = 439
	TokNAMESPACE               TokenType = 440
	TokEXPORT                  TokenType = 441
	TokHIVE_TOKEN_STREAM       TokenType = 442
	TokSENTINEL                TokenType = 443
)

var tokenTypeNames = map[TokenType]string{
	TokL_PAREN:                 "L_PAREN",
	TokR_PAREN:                 "R_PAREN",
	TokL_BRACKET:               "L_BRACKET",
	TokR_BRACKET:               "R_BRACKET",
	TokL_BRACE:                 "L_BRACE",
	TokR_BRACE:                 "R_BRACE",
	TokCOMMA:                   "COMMA",
	TokDOT:                     "DOT",
	TokDASH:                    "DASH",
	TokPLUS:                    "PLUS",
	TokCOLON:                   "COLON",
	TokDOTCOLON:                "DOTCOLON",
	TokDOTCARET:                "DOTCARET",
	TokDCOLON:                  "DCOLON",
	TokDCOLONDOLLAR:            "DCOLONDOLLAR",
	TokDCOLONPERCENT:           "DCOLONPERCENT",
	TokDCOLONQMARK:             "DCOLONQMARK",
	TokDQMARK:                  "DQMARK",
	TokSEMICOLON:               "SEMICOLON",
	TokSTAR:                    "STAR",
	TokBACKSLASH:               "BACKSLASH",
	TokSLASH:                   "SLASH",
	TokLT:                      "LT",
	TokLTE:                     "LTE",
	TokGT:                      "GT",
	TokGTE:                     "GTE",
	TokNOT:                     "NOT",
	TokEQ:                      "EQ",
	TokNEQ:                     "NEQ",
	TokNULLSAFE_EQ:             "NULLSAFE_EQ",
	TokCOLON_EQ:                "COLON_EQ",
	TokCOLON_GT:                "COLON_GT",
	TokNCOLON_GT:               "NCOLON_GT",
	TokAND:                     "AND",
	TokOR:                      "OR",
	TokAMP:                     "AMP",
	TokDPIPE:                   "DPIPE",
	TokPIPE_GT:                 "PIPE_GT",
	TokPIPE:                    "PIPE",
	TokPIPE_SLASH:              "PIPE_SLASH",
	TokDPIPE_SLASH:             "DPIPE_SLASH",
	TokCARET:                   "CARET",
	TokCARET_AT:                "CARET_AT",
	TokTILDE:                   "TILDE",
	TokARROW:                   "ARROW",
	TokDARROW:                  "DARROW",
	TokFARROW:                  "FARROW",
	TokHASH:                    "HASH",
	TokHASH_ARROW:              "HASH_ARROW",
	TokDHASH_ARROW:             "DHASH_ARROW",
	TokLR_ARROW:                "LR_ARROW",
	TokLLRR_ARROW:              "LLRR_ARROW",
	TokDAT:                     "DAT",
	TokAT_QMARK:                "AT_QMARK",
	TokLT_AT:                   "LT_AT",
	TokAT_GT:                   "AT_GT",
	TokDOLLAR:                  "DOLLAR",
	TokPARAMETER:               "PARAMETER",
	TokSESSION:                 "SESSION",
	TokSESSION_PARAMETER:       "SESSION_PARAMETER",
	TokSESSION_USER:            "SESSION_USER",
	TokDAMP:                    "DAMP",
	TokAMP_LT:                  "AMP_LT",
	TokAMP_GT:                  "AMP_GT",
	TokADJACENT:                "ADJACENT",
	TokXOR:                     "XOR",
	TokDSTAR:                   "DSTAR",
	TokQMARK_AMP:               "QMARK_AMP",
	TokQMARK_PIPE:              "QMARK_PIPE",
	TokHASH_DASH:               "HASH_DASH",
	TokEXCLAMATION:             "EXCLAMATION",
	TokURI_START:               "URI_START",
	TokBLOCK_START:             "BLOCK_START",
	TokBLOCK_END:               "BLOCK_END",
	TokSPACE:                   "SPACE",
	TokBREAK:                   "BREAK",
	TokSTRING:                  "STRING",
	TokNUMBER:                  "NUMBER",
	TokIDENTIFIER:              "IDENTIFIER",
	TokDATABASE:                "DATABASE",
	TokCOLUMN:                  "COLUMN",
	TokCOLUMN_DEF:              "COLUMN_DEF",
	TokSCHEMA:                  "SCHEMA",
	TokTABLE:                   "TABLE",
	TokWAREHOUSE:               "WAREHOUSE",
	TokSTAGE:                   "STAGE",
	TokSTREAM:                  "STREAM",
	TokSTREAMLIT:               "STREAMLIT",
	TokVAR:                     "VAR",
	TokBIT_STRING:              "BIT_STRING",
	TokHEX_STRING:              "HEX_STRING",
	TokBYTE_STRING:             "BYTE_STRING",
	TokNATIONAL_STRING:         "NATIONAL_STRING",
	TokRAW_STRING:              "RAW_STRING",
	TokHEREDOC_STRING:          "HEREDOC_STRING",
	TokUNICODE_STRING:          "UNICODE_STRING",
	TokBIT:                     "BIT",
	TokBOOLEAN:                 "BOOLEAN",
	TokTINYINT:                 "TINYINT",
	TokUTINYINT:                "UTINYINT",
	TokSMALLINT:                "SMALLINT",
	TokUSMALLINT:               "USMALLINT",
	TokMEDIUMINT:               "MEDIUMINT",
	TokUMEDIUMINT:              "UMEDIUMINT",
	TokINT:                     "INT",
	TokUINT:                    "UINT",
	TokBIGINT:                  "BIGINT",
	TokUBIGINT:                 "UBIGINT",
	TokBIGNUM:                  "BIGNUM",
	TokINT128:                  "INT128",
	TokUINT128:                 "UINT128",
	TokINT256:                  "INT256",
	TokUINT256:                 "UINT256",
	TokFLOAT:                   "FLOAT",
	TokDOUBLE:                  "DOUBLE",
	TokUDOUBLE:                 "UDOUBLE",
	TokDECIMAL:                 "DECIMAL",
	TokDECIMAL32:               "DECIMAL32",
	TokDECIMAL64:               "DECIMAL64",
	TokDECIMAL128:              "DECIMAL128",
	TokDECIMAL256:              "DECIMAL256",
	TokDECFLOAT:                "DECFLOAT",
	TokUDECIMAL:                "UDECIMAL",
	TokBIGDECIMAL:              "BIGDECIMAL",
	TokCHAR:                    "CHAR",
	TokNCHAR:                   "NCHAR",
	TokVARCHAR:                 "VARCHAR",
	TokNVARCHAR:                "NVARCHAR",
	TokBPCHAR:                  "BPCHAR",
	TokTEXT:                    "TEXT",
	TokMEDIUMTEXT:              "MEDIUMTEXT",
	TokLONGTEXT:                "LONGTEXT",
	TokBLOB:                    "BLOB",
	TokMEDIUMBLOB:              "MEDIUMBLOB",
	TokLONGBLOB:                "LONGBLOB",
	TokTINYBLOB:                "TINYBLOB",
	TokTINYTEXT:                "TINYTEXT",
	TokNAME:                    "NAME",
	TokBINARY:                  "BINARY",
	TokVARBINARY:               "VARBINARY",
	TokJSON:                    "JSON",
	TokJSONB:                   "JSONB",
	TokTIME:                    "TIME",
	TokTIMETZ:                  "TIMETZ",
	TokTIME_NS:                 "TIME_NS",
	TokTIMESTAMP:               "TIMESTAMP",
	TokTIMESTAMPTZ:             "TIMESTAMPTZ",
	TokTIMESTAMPLTZ:            "TIMESTAMPLTZ",
	TokTIMESTAMPNTZ:            "TIMESTAMPNTZ",
	TokTIMESTAMP_S:             "TIMESTAMP_S",
	TokTIMESTAMP_MS:            "TIMESTAMP_MS",
	TokTIMESTAMP_NS:            "TIMESTAMP_NS",
	TokDATETIME:                "DATETIME",
	TokDATETIME2:               "DATETIME2",
	TokDATETIME64:              "DATETIME64",
	TokSMALLDATETIME:           "SMALLDATETIME",
	TokDATE:                    "DATE",
	TokDATE32:                  "DATE32",
	TokINT4RANGE:               "INT4RANGE",
	TokINT4MULTIRANGE:          "INT4MULTIRANGE",
	TokINT8RANGE:               "INT8RANGE",
	TokINT8MULTIRANGE:          "INT8MULTIRANGE",
	TokNUMRANGE:                "NUMRANGE",
	TokNUMMULTIRANGE:           "NUMMULTIRANGE",
	TokTSRANGE:                 "TSRANGE",
	TokTSMULTIRANGE:            "TSMULTIRANGE",
	TokTSTZRANGE:               "TSTZRANGE",
	TokTSTZMULTIRANGE:          "TSTZMULTIRANGE",
	TokDATERANGE:               "DATERANGE",
	TokDATEMULTIRANGE:          "DATEMULTIRANGE",
	TokUUID:                    "UUID",
	TokGEOGRAPHY:               "GEOGRAPHY",
	TokGEOGRAPHYPOINT:          "GEOGRAPHYPOINT",
	TokNULLABLE:                "NULLABLE",
	TokGEOMETRY:                "GEOMETRY",
	TokPOINT:                   "POINT",
	TokRING:                    "RING",
	TokLINESTRING:              "LINESTRING",
	TokLOCALTIME:               "LOCALTIME",
	TokLOCALTIMESTAMP:          "LOCALTIMESTAMP",
	TokSYSTIMESTAMP:            "SYSTIMESTAMP",
	TokMULTILINESTRING:         "MULTILINESTRING",
	TokPOLYGON:                 "POLYGON",
	TokMULTIPOLYGON:            "MULTIPOLYGON",
	TokHLLSKETCH:               "HLLSKETCH",
	TokHSTORE:                  "HSTORE",
	TokSUPER:                   "SUPER",
	TokSERIAL:                  "SERIAL",
	TokSMALLSERIAL:             "SMALLSERIAL",
	TokBIGSERIAL:               "BIGSERIAL",
	TokXML:                     "XML",
	TokYEAR:                    "YEAR",
	TokUSERDEFINED:             "USERDEFINED",
	TokMONEY:                   "MONEY",
	TokSMALLMONEY:              "SMALLMONEY",
	TokROWVERSION:              "ROWVERSION",
	TokIMAGE:                   "IMAGE",
	TokVARIANT:                 "VARIANT",
	TokOBJECT:                  "OBJECT",
	TokINET:                    "INET",
	TokIPADDRESS:               "IPADDRESS",
	TokIPPREFIX:                "IPPREFIX",
	TokIPV4:                    "IPV4",
	TokIPV6:                    "IPV6",
	TokENUM:                    "ENUM",
	TokENUM8:                   "ENUM8",
	TokENUM16:                  "ENUM16",
	TokFIXEDSTRING:             "FIXEDSTRING",
	TokLOWCARDINALITY:          "LOWCARDINALITY",
	TokNESTED:                  "NESTED",
	TokAGGREGATEFUNCTION:       "AGGREGATEFUNCTION",
	TokSIMPLEAGGREGATEFUNCTION: "SIMPLEAGGREGATEFUNCTION",
	TokTDIGEST:                 "TDIGEST",
	TokUNKNOWN:                 "UNKNOWN",
	TokVECTOR:                  "VECTOR",
	TokDYNAMIC:                 "DYNAMIC",
	TokVOID:                    "VOID",
	TokALIAS:                   "ALIAS",
	TokALTER:                   "ALTER",
	TokALL:                     "ALL",
	TokANTI:                    "ANTI",
	TokANY:                     "ANY",
	TokAPPLY:                   "APPLY",
	TokARRAY:                   "ARRAY",
	TokASC:                     "ASC",
	TokASOF:                    "ASOF",
	TokATTACH:                  "ATTACH",
	TokAUTO_INCREMENT:          "AUTO_INCREMENT",
	TokBEGIN:                   "BEGIN",
	TokBETWEEN:                 "BETWEEN",
	TokBULK_COLLECT_INTO:       "BULK_COLLECT_INTO",
	TokCACHE:                   "CACHE",
	TokCASE:                    "CASE",
	TokCHARACTER_SET:           "CHARACTER_SET",
	TokCLUSTER_BY:              "CLUSTER_BY",
	TokCOLLATE:                 "COLLATE",
	TokCOMMAND:                 "COMMAND",
	TokCOMMENT:                 "COMMENT",
	TokCOMMIT:                  "COMMIT",
	TokCONNECT_BY:              "CONNECT_BY",
	TokCONSTRAINT:              "CONSTRAINT",
	TokCOPY:                    "COPY",
	TokCREATE:                  "CREATE",
	TokCROSS:                   "CROSS",
	TokCUBE:                    "CUBE",
	TokCURRENT_DATE:            "CURRENT_DATE",
	TokCURRENT_DATETIME:        "CURRENT_DATETIME",
	TokCURRENT_SCHEMA:          "CURRENT_SCHEMA",
	TokCURRENT_TIME:            "CURRENT_TIME",
	TokCURRENT_TIMESTAMP:       "CURRENT_TIMESTAMP",
	TokCURRENT_USER:            "CURRENT_USER",
	TokCURRENT_USER_ID:         "CURRENT_USER_ID",
	TokCURRENT_ROLE:            "CURRENT_ROLE",
	TokCURRENT_CATALOG:         "CURRENT_CATALOG",
	TokDECLARE:                 "DECLARE",
	TokDEFAULT:                 "DEFAULT",
	TokDELETE:                  "DELETE",
	TokDESC:                    "DESC",
	TokDESCRIBE:                "DESCRIBE",
	TokDETACH:                  "DETACH",
	TokDICTIONARY:              "DICTIONARY",
	TokDISTINCT:                "DISTINCT",
	TokDISTRIBUTE_BY:           "DISTRIBUTE_BY",
	TokDIV:                     "DIV",
	TokDROP:                    "DROP",
	TokELSE:                    "ELSE",
	TokEND:                     "END",
	TokESCAPE:                  "ESCAPE",
	TokEXCEPT:                  "EXCEPT",
	TokEXECUTE:                 "EXECUTE",
	TokEXISTS:                  "EXISTS",
	TokFALSE:                   "FALSE",
	TokFETCH:                   "FETCH",
	TokFILE:                    "FILE",
	TokFILE_FORMAT:             "FILE_FORMAT",
	TokFILTER:                  "FILTER",
	TokFINAL:                   "FINAL",
	TokFIRST:                   "FIRST",
	TokFOR:                     "FOR",
	TokFORCE:                   "FORCE",
	TokFOREIGN_KEY:             "FOREIGN_KEY",
	TokFORMAT:                  "FORMAT",
	TokFROM:                    "FROM",
	TokFULL:                    "FULL",
	TokFUNCTION:                "FUNCTION",
	TokGET:                     "GET",
	TokGLOB:                    "GLOB",
	TokGLOBAL:                  "GLOBAL",
	TokGRANT:                   "GRANT",
	TokGROUP_BY:                "GROUP_BY",
	TokGROUPING_SETS:           "GROUPING_SETS",
	TokHAVING:                  "HAVING",
	TokHINT:                    "HINT",
	TokIGNORE:                  "IGNORE",
	TokILIKE:                   "ILIKE",
	TokIN:                      "IN",
	TokINDEX:                   "INDEX",
	TokINDEXED_BY:              "INDEXED_BY",
	TokINNER:                   "INNER",
	TokINSERT:                  "INSERT",
	TokINSTALL:                 "INSTALL",
	TokINTEGRATION:             "INTEGRATION",
	TokINTERSECT:               "INTERSECT",
	TokINTERVAL:                "INTERVAL",
	TokINTO:                    "INTO",
	TokINTRODUCER:              "INTRODUCER",
	TokIRLIKE:                  "IRLIKE",
	TokIS:                      "IS",
	TokISNULL:                  "ISNULL",
	TokJOIN:                    "JOIN",
	TokJOIN_MARKER:             "JOIN_MARKER",
	TokKEEP:                    "KEEP",
	TokKEY:                     "KEY",
	TokKILL:                    "KILL",
	TokLANGUAGE:                "LANGUAGE",
	TokLATERAL:                 "LATERAL",
	TokLEFT:                    "LEFT",
	TokLIKE:                    "LIKE",
	TokLIMIT:                   "LIMIT",
	TokLIST:                    "LIST",
	TokLOAD:                    "LOAD",
	TokLOCK:                    "LOCK",
	TokMAP:                     "MAP",
	TokMATCH:                   "MATCH",
	TokMATCH_CONDITION:         "MATCH_CONDITION",
	TokMATCH_RECOGNIZE:         "MATCH_RECOGNIZE",
	TokMEMBER_OF:               "MEMBER_OF",
	TokMERGE:                   "MERGE",
	TokMOD:                     "MOD",
	TokMODEL:                   "MODEL",
	TokNATURAL:                 "NATURAL",
	TokNEXT:                    "NEXT",
	TokNOTHING:                 "NOTHING",
	TokNOTNULL:                 "NOTNULL",
	TokNULL:                    "NULL",
	TokOBJECT_IDENTIFIER:       "OBJECT_IDENTIFIER",
	TokOFFSET:                  "OFFSET",
	TokON:                      "ON",
	TokONLY:                    "ONLY",
	TokOPERATOR:                "OPERATOR",
	TokORDER_BY:                "ORDER_BY",
	TokORDER_SIBLINGS_BY:       "ORDER_SIBLINGS_BY",
	TokORDERED:                 "ORDERED",
	TokORDINALITY:              "ORDINALITY",
	TokOUT:                     "OUT",
	TokINOUT:                   "INOUT",
	TokOUTER:                   "OUTER",
	TokOVER:                    "OVER",
	TokOVERLAPS:                "OVERLAPS",
	TokOVERWRITE:               "OVERWRITE",
	TokPACKAGE:                 "PACKAGE",
	TokPARTITION:               "PARTITION",
	TokPARTITION_BY:            "PARTITION_BY",
	TokPERCENT:                 "PERCENT",
	TokPIVOT:                   "PIVOT",
	TokPLACEHOLDER:             "PLACEHOLDER",
	TokPOLICY:                  "POLICY",
	TokPOOL:                    "POOL",
	TokPOSITIONAL:              "POSITIONAL",
	TokPRAGMA:                  "PRAGMA",
	TokPREWHERE:                "PREWHERE",
	TokPRIMARY_KEY:             "PRIMARY_KEY",
	TokPROCEDURE:               "PROCEDURE",
	TokPROPERTIES:              "PROPERTIES",
	TokPROJECTION:              "PROJECTION",
	TokPSEUDO_TYPE:             "PSEUDO_TYPE",
	TokPUT:                     "PUT",
	TokQUALIFY:                 "QUALIFY",
	TokQUOTE:                   "QUOTE",
	TokQDCOLON:                 "QDCOLON",
	TokRANGE:                   "RANGE",
	TokRECURSIVE:               "RECURSIVE",
	TokREFRESH:                 "REFRESH",
	TokRENAME:                  "RENAME",
	TokREPLACE:                 "REPLACE",
	TokRETURNING:               "RETURNING",
	TokREVOKE:                  "REVOKE",
	TokREFERENCES:              "REFERENCES",
	TokRIGHT:                   "RIGHT",
	TokRLIKE:                   "RLIKE",
	TokROLE:                    "ROLE",
	TokROLLBACK:                "ROLLBACK",
	TokROLLUP:                  "ROLLUP",
	TokROW:                     "ROW",
	TokROWS:                    "ROWS",
	TokRULE:                    "RULE",
	TokSELECT:                  "SELECT",
	TokSEMI:                    "SEMI",
	TokSEPARATOR:               "SEPARATOR",
	TokSEQUENCE:                "SEQUENCE",
	TokSERDE_PROPERTIES:        "SERDE_PROPERTIES",
	TokSET:                     "SET",
	TokSETTINGS:                "SETTINGS",
	TokSHOW:                    "SHOW",
	TokSIMILAR_TO:              "SIMILAR_TO",
	TokSOME:                    "SOME",
	TokSORT_BY:                 "SORT_BY",
	TokSOUNDS_LIKE:             "SOUNDS_LIKE",
	TokSQL_SECURITY:            "SQL_SECURITY",
	TokSTART_WITH:              "START_WITH",
	TokSTORAGE_INTEGRATION:     "STORAGE_INTEGRATION",
	TokSTRAIGHT_JOIN:           "STRAIGHT_JOIN",
	TokSTRUCT:                  "STRUCT",
	TokSUMMARIZE:               "SUMMARIZE",
	TokTABLE_SAMPLE:            "TABLE_SAMPLE",
	TokTAG:                     "TAG",
	TokTEMPORARY:               "TEMPORARY",
	TokTOP:                     "TOP",
	TokTHEN:                    "THEN",
	TokTRUE:                    "TRUE",
	TokTRUNCATE:                "TRUNCATE",
	TokTRIGGER:                 "TRIGGER",
	TokTYPE:                    "TYPE",
	TokUNCACHE:                 "UNCACHE",
	TokUNDROP:                  "UNDROP",
	TokUNION:                   "UNION",
	TokUNNEST:                  "UNNEST",
	TokUNPIVOT:                 "UNPIVOT",
	TokUPDATE:                  "UPDATE",
	TokUSE:                     "USE",
	TokUSING:                   "USING",
	TokVALUES:                  "VALUES",
	TokVARIADIC:                "VARIADIC",
	TokVIEW:                    "VIEW",
	TokSEMANTIC_VIEW:           "SEMANTIC_VIEW",
	TokVOLATILE:                "VOLATILE",
	TokVOLUME:                  "VOLUME",
	TokWHEN:                    "WHEN",
	TokWHERE:                   "WHERE",
	TokWINDOW:                  "WINDOW",
	TokWITH:                    "WITH",
	TokUNIQUE:                  "UNIQUE",
	TokUTC_DATE:                "UTC_DATE",
	TokUTC_TIME:                "UTC_TIME",
	TokUTC_TIMESTAMP:           "UTC_TIMESTAMP",
	TokOPTION:                  "OPTION",
	TokSINK:                    "SINK",
	TokSOURCE:                  "SOURCE",
	TokANALYZE:                 "ANALYZE",
	TokNAMESPACE:               "NAMESPACE",
	TokEXPORT:                  "EXPORT",
	TokHIVE_TOKEN_STREAM:       "HIVE_TOKEN_STREAM",
	TokSENTINEL:                "SENTINEL",
}

var tokenTypesByName = func() map[string]TokenType {
	m := make(map[string]TokenType, len(tokenTypeNames))
	for t, n := range tokenTypeNames {
		m[n] = t
	}
	return m
}()

// String renders the token type the way the reference's __str__ does.
func (t TokenType) String() string {
	if n, ok := tokenTypeNames[t]; ok {
		return "TokenType." + n
	}
	return "TokenType(?)"
}

// TokenTypeByName looks a token type up by its reference name, for tests
// and for reading the token expectations.
func TokenTypeByName(name string) (TokenType, bool) {
	t, ok := tokenTypesByName[name]
	return t, ok
}
