package sqlglot

import "testing"

// A trigger with nothing to EXECUTE is kept as text, as the reference keeps
// it (MySQL's BEGIN ... END bodies). DuckDB writes only a trigger's name.
// A semicolon ends the statement, so the text after it is refused.
func TestTriggerCommands(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION F()"},
		{"", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"tsql", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"tsql", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"tsql", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION F()"},
		{"tsql", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"duckdb", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"duckdb", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"duckdb", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t"},
		{"duckdb", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"mysql", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"mysql", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"mysql", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION F()"},
		{"mysql", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
	} {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			t.Errorf("[%s] ParseOne(%q): %v", c[0], c[1], err)
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			t.Errorf("[%s] Generate(%q): %v", c[0], c[1], err)
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written != 44 {
		t.Errorf("wrote %d statements, want 44", written)
	}
	// The text after a semicolon is another statement.
	sql := "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1; END"
	for _, dialect := range []string{"", "tsql", "duckdb", "mysql"} {
		if _, err := ParseOne(sql, dialect); err == nil {
			t.Errorf("[%s] read two statements as one", dialect)
		}
	}
}
