package sqlglot

import "testing"

// A trigger with nothing to EXECUTE is kept as text, as the reference keeps
// it (MySQL's BEGIN ... END bodies); the Command stops at a semicolon; and
// DuckDB, which writes only a trigger's name, is declined. Held to the
// pinned reference: what the port writes must be what it writes.
func TestTriggerCommands(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION F()"},
		{"", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1; END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"tsql", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"tsql", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"tsql", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION F()"},
		{"tsql", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1; END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"tsql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"duckdb", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"duckdb", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"duckdb", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t"},
		{"duckdb", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1; END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"duckdb", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END", "CREATE TRIGGER check_age BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.created_at = NOW() END"},
		{"mysql", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END", "CREATE TRIGGER t AFTER UPDATE ON a FOR EACH ROW BEGIN INSERT INTO l (x) VALUES (OLD.x) END"},
		{"mysql", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1", "CREATE TRIGGER t BEFORE DELETE ON o FOR EACH ROW UPDATE s SET c = c + 1"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u", "CREATE TRIGGER t BEFORE INSERT ON u"},
		{"mysql", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE OR REPLACE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END", "CREATE TRIGGER t AFTER INSERT ON u FOR EACH ROW WHEN (a > 1) BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION f()", "CREATE TRIGGER t INSTEAD OF INSERT ON u FOR EACH ROW EXECUTE FUNCTION F()"},
		{"mysql", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END", "CREATE CONSTRAINT TRIGGER t AFTER INSERT ON u FOR EACH ROW BEGIN SELECT 1 END"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1; END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW FOLLOWS x SET a = 1"},
		{"mysql", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END", "CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW -- c\nBEGIN SELECT 1 END"},
	} {
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written < 20 {
		t.Errorf("only %d statements were written back", written)
	}
	// The text after a semicolon is another statement.
	if _, err := ParseOne("CREATE TRIGGER t BEFORE INSERT ON u FOR EACH ROW BEGIN SELECT 1; END", "mysql"); err == nil {
		t.Error("read two statements as one")
	}
}
