package sqlglot

import "testing"

// SECURITY on a view -- MySQL's SQL SECURITY ahead of the kind, Presto's bare
// SECURITY after the name -- and the words in front of a routine, which the
// port declines rather than drop; all held to the pinned reference.
func TestViewSecurity(t *testing.T) {
	written := 0
	for _, c := range [][3]string{
		{"", "CREATE OR REPLACE VIEW v SECURITY DEFINER AS SELECT id FROM t", "CREATE OR REPLACE VIEW v SQL SECURITY DEFINER AS SELECT id FROM t"},
		{"", "CREATE OR REPLACE VIEW v SECURITY INVOKER AS SELECT id FROM t", "CREATE OR REPLACE VIEW v SQL SECURITY INVOKER AS SELECT id FROM t"},
		{"", "CREATE SQL SECURITY INVOKER VIEW id_test (id, foo) AS SELECT 0, foo FROM test", "CREATE VIEW id_test (id, foo) SQL SECURITY INVOKER AS SELECT 0, foo FROM test"},
		{"", "CREATE SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE VIEW v SQL SECURITY DEFINER AS SELECT 1"},
		{"", "CREATE OR REPLACE SQL SECURITY NONE VIEW v AS SELECT 1", "CREATE OR REPLACE VIEW v SQL SECURITY NONE AS SELECT 1"},
		{"", "CREATE ALGORITHM=MERGE SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE ALGORITHM=MERGE VIEW v SQL SECURITY DEFINER AS SELECT 1"},
		{"", "CREATE VIEW v SECURITY NONE AS SELECT 1", "CREATE VIEW v SQL SECURITY NONE AS SELECT 1"},
		{"", "CREATE VIEW v SECURITY AS SELECT 1", "CREATE VIEW v SQL SECURITY  AS SELECT 1"},
		{"", "CREATE SQL SECURITY VIEW v AS SELECT 1", "CREATE VIEW v SQL SECURITY  AS SELECT 1"},
		{"", "CREATE SECURITY DEFINER VIEW v AS SELECT 1", "CREATE VIEW v SQL SECURITY DEFINER AS SELECT 1"},
		{"", "CREATE DEFINER=x@y SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE DEFINER=x@y VIEW v SQL SECURITY DEFINER AS SELECT 1"},
		{"", "CREATE SQL SECURITY DEFINER DEFINER=x@y VIEW v AS SELECT 1", "CREATE DEFINER=x@y VIEW v SQL SECURITY DEFINER AS SELECT 1"},
		{"", "CREATE ALGORITHM=MERGE VIEW v SQL SECURITY DEFINER AS SELECT 1", "CREATE ALGORITHM=MERGE VIEW v SQL SECURITY DEFINER AS SELECT 1"},
		{"", "CREATE VIEW v SQL SECURITY DEFINER SECURITY INVOKER AS SELECT 1", "CREATE VIEW v SQL SECURITY DEFINER SQL SECURITY INVOKER AS SELECT 1"},
		{"", "CREATE SQL SECURITY DEFINER OR REPLACE VIEW v AS SELECT 1", "CREATE SQL SECURITY DEFINER OR REPLACE VIEW v AS SELECT 1"},
		{"presto", "CREATE OR REPLACE VIEW v SECURITY DEFINER AS SELECT id FROM t", "CREATE OR REPLACE VIEW v SECURITY DEFINER AS SELECT id FROM t"},
		{"presto", "CREATE OR REPLACE VIEW v SECURITY INVOKER AS SELECT id FROM t", "CREATE OR REPLACE VIEW v SECURITY INVOKER AS SELECT id FROM t"},
		{"presto", "CREATE SQL SECURITY INVOKER VIEW id_test (id, foo) AS SELECT 0, foo FROM test", "CREATE VIEW id_test SECURITY INVOKER AS SELECT 0, foo FROM test"},
		{"presto", "CREATE SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE VIEW v SECURITY DEFINER AS SELECT 1"},
		{"presto", "CREATE OR REPLACE SQL SECURITY NONE VIEW v AS SELECT 1", "CREATE OR REPLACE VIEW v SECURITY NONE AS SELECT 1"},
		{"presto", "CREATE ALGORITHM=MERGE SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE ALGORITHM=MERGE VIEW v SECURITY DEFINER AS SELECT 1"},
		{"presto", "CREATE VIEW v SECURITY NONE AS SELECT 1", "CREATE VIEW v SECURITY NONE AS SELECT 1"},
		{"presto", "CREATE VIEW v SECURITY AS SELECT 1", "CREATE VIEW v SECURITY  AS SELECT 1"},
		{"presto", "CREATE SQL SECURITY VIEW v AS SELECT 1", "CREATE VIEW v SECURITY  AS SELECT 1"},
		{"presto", "CREATE SECURITY DEFINER VIEW v AS SELECT 1", "CREATE VIEW v SECURITY DEFINER AS SELECT 1"},
		{"presto", "CREATE DEFINER=x@y SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE DEFINER=x@y VIEW v SECURITY DEFINER AS SELECT 1"},
		{"presto", "CREATE SQL SECURITY DEFINER DEFINER=x@y VIEW v AS SELECT 1", "CREATE DEFINER=x@y VIEW v SECURITY DEFINER AS SELECT 1"},
		{"presto", "CREATE ALGORITHM=MERGE VIEW v SQL SECURITY DEFINER AS SELECT 1", "CREATE ALGORITHM=MERGE VIEW v SECURITY DEFINER AS SELECT 1"},
		{"presto", "CREATE VIEW v SQL SECURITY DEFINER SECURITY INVOKER AS SELECT 1", "CREATE VIEW v SECURITY DEFINER SECURITY INVOKER AS SELECT 1"},
		{"presto", "CREATE SQL SECURITY DEFINER OR REPLACE VIEW v AS SELECT 1", "CREATE SQL SECURITY DEFINER OR REPLACE VIEW v AS SELECT 1"},
		{"mysql", "CREATE OR REPLACE VIEW v SECURITY DEFINER AS SELECT id FROM t", "CREATE OR REPLACE SQL SECURITY DEFINER VIEW v AS SELECT id FROM t"},
		{"mysql", "CREATE OR REPLACE VIEW v SECURITY INVOKER AS SELECT id FROM t", "CREATE OR REPLACE SQL SECURITY INVOKER VIEW v AS SELECT id FROM t"},
		{"mysql", "CREATE SQL SECURITY INVOKER VIEW id_test (id, foo) AS SELECT 0, foo FROM test", "CREATE SQL SECURITY INVOKER VIEW id_test (id, foo) AS SELECT 0, foo FROM test"},
		{"mysql", "CREATE SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE SQL SECURITY DEFINER VIEW v AS SELECT 1"},
		{"mysql", "CREATE OR REPLACE SQL SECURITY NONE VIEW v AS SELECT 1", "CREATE OR REPLACE SQL SECURITY NONE VIEW v AS SELECT 1"},
		{"mysql", "CREATE ALGORITHM=MERGE SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE ALGORITHM=MERGE SQL SECURITY DEFINER VIEW v AS SELECT 1"},
		{"mysql", "CREATE VIEW v SECURITY NONE AS SELECT 1", "CREATE SQL SECURITY NONE VIEW v AS SELECT 1"},
		{"mysql", "CREATE VIEW v SECURITY AS SELECT 1", "CREATE SQL SECURITY  VIEW v AS SELECT 1"},
		{"mysql", "CREATE SQL SECURITY VIEW v AS SELECT 1", "CREATE SQL SECURITY  VIEW v AS SELECT 1"},
		{"mysql", "CREATE SECURITY DEFINER VIEW v AS SELECT 1", "CREATE SQL SECURITY DEFINER VIEW v AS SELECT 1"},
		{"mysql", "CREATE DEFINER=x@y SQL SECURITY DEFINER VIEW v AS SELECT 1", "CREATE DEFINER=x@y SQL SECURITY DEFINER VIEW v AS SELECT 1"},
		{"mysql", "CREATE SQL SECURITY DEFINER DEFINER=x@y VIEW v AS SELECT 1", "CREATE DEFINER=x@y SQL SECURITY DEFINER VIEW v AS SELECT 1"},
		{"mysql", "CREATE ALGORITHM=MERGE VIEW v SQL SECURITY DEFINER AS SELECT 1", "CREATE ALGORITHM=MERGE SQL SECURITY DEFINER VIEW v AS SELECT 1"},
		{"mysql", "CREATE VIEW v SQL SECURITY DEFINER SECURITY INVOKER AS SELECT 1", "CREATE SQL SECURITY DEFINER VIEW v SQL SECURITY INVOKER AS SELECT 1"},
		{"mysql", "CREATE SQL SECURITY DEFINER OR REPLACE VIEW v AS SELECT 1", "CREATE SQL SECURITY DEFINER OR REPLACE VIEW v AS SELECT 1"},
	} {
		// Some of these the port declines, which is allowed; what it does
		// write must be what the reference writes.
		tree, err := ParseOne(c[1], c[0])
		if err != nil {
			continue
		}
		got, err := Generate(tree, c[0])
		if err != nil {
			continue
		}
		written++
		if got != c[2] {
			t.Errorf("[%s] %s\n  want %s\n  got  %s", c[0], c[1], c[2], got)
		}
	}
	if written < 20 {
		t.Errorf("only %d statements were written back", written)
	}
	for _, sql := range []string{
		"CREATE SQL SECURITY DEFINER FUNCTION f() RETURNS INT RETURN 1",
		"CREATE DEFINER=x@y FUNCTION f() RETURNS INT RETURN 1",
		"CREATE SQL SECURITY DEFINER TABLE t (a INT)",
	} {
		if _, err := ParseOne(sql, "mysql"); err == nil {
			t.Errorf("read %s, whose leading words would be dropped", sql)
		}
	}
}
