"""Generate sqlglot/classes_gen.go: which module each expression class lives in.

    python harness/gen_classes.py > sqlglot/classes_gen.go

Read from the committed expectations rather than from sqlglot's source, so the
table describes exactly the classes the corpus exercises, and regenerating it
needs no Python dependencies beyond the standard library.
"""

import collections
import glob
import json

pairs = set()
for f in glob.glob("testdata/expected/*.json"):
    if f.endswith("index.json"):
        continue
    for rec in json.load(open(f))["tree"]:
        c = rec.get("c", "")
        if c.startswith("sqlglot.expressions."):
            mod, cls = c[len("sqlglot.expressions.") :].rsplit(".", 1)
            pairs.add((cls, mod))
by_mod = collections.defaultdict(list)
for cls, mod in sorted(pairs):
    by_mod[mod].append(cls)
print("// Code generated by harness/gen_classes.py from the reference corpus. DO NOT EDIT.")
print("//")
print("// The module each expression class lives in, in the reference. Dump needs")
print("// it to qualify class names the way the reference does; a class absent here")
print('// dumps under "core" and shows up as a mismatch, which is the right failure.')
print()
print("package sqlglot")
print()
print("var classModule = map[string]string{")
for mod in sorted(by_mod):
    print(f"\t// {mod}")
    for cls in by_mod[mod]:
        print(f'\t"{cls}": "{mod}",')
print("}")
