"""Generate the tokenizer's data tables from the pinned sqlglot reference.

    python harness/gen_tokenizer.py --sqlglot ~/opensource/sqlglot

Writes sqlglot/tokentype_gen.go (the TokenType enum) and sqlglot/dialects_gen.go
(one resolved tokenizer configuration per dialect the executor uses).

These tables are DATA, not logic: roughly 3,000 keyword mappings that would be
transcription errors waiting to happen if typed by hand. The tokenizer's
algorithm is ported by hand in sqlglot/tokenizer.go; only the tables it reads
are generated. Regenerating against a different reference commit is refused --
same pin, same rule as harness/oracle.py.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

# "" is the dialect-neutral default, matching oracle.py's corpus.
DIALECTS = ("", "tsql", "postgres", "duckdb", "databricks")

HEADER = "// Code generated by harness/gen_tokenizer.py from the pinned reference. DO NOT EDIT.\n//\n"


def gostr(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def gen_tokentypes(TokenType) -> str:
    members = sorted(TokenType, key=lambda m: m.value)
    lines = [
        HEADER,
        "// The token types the reference defines, with the reference's own ordinals so\n",
        "// a generated table and a hand-written switch cannot drift apart silently.\n\n",
        "package sqlglot\n\n",
        "// TokenType identifies a lexical token. Values match the reference's IntEnum.\n",
        "type TokenType int\n\n",
        "const (\n",
    ]
    for m in members:
        lines.append(f"\tTok{m.name} TokenType = {m.value}\n")
    lines.append(")\n\n")
    lines.append("var tokenTypeNames = map[TokenType]string{\n")
    for m in members:
        lines.append(f"\tTok{m.name}: {gostr(m.name)},\n")
    lines.append("}\n\n")
    lines.append("var tokenTypesByName = func() map[string]TokenType {\n")
    lines.append("\tm := make(map[string]TokenType, len(tokenTypeNames))\n")
    lines.append("\tfor t, n := range tokenTypeNames {\n\t\tm[n] = t\n\t}\n\treturn m\n}()\n\n")
    lines.append("// String renders the token type the way the reference's __str__ does.\n")
    lines.append("func (t TokenType) String() string {\n")
    lines.append("\tif n, ok := tokenTypeNames[t]; ok {\n\t\treturn \"TokenType.\" + n\n\t}\n")
    lines.append("\treturn \"TokenType(?)\"\n}\n\n")
    lines.append("// TokenTypeByName looks a token type up by its reference name, for tests\n")
    lines.append("// and for reading the token expectations.\n")
    lines.append("func TokenTypeByName(name string) (TokenType, bool) {\n")
    lines.append("\tt, ok := tokenTypesByName[name]\n\treturn t, ok\n}\n")
    return "".join(lines)


def strmap(name: str, d: dict) -> str:
    if not d:
        return f"\t\t{name}: nil,\n"
    body = "".join(f"\t\t\t{gostr(k)}: {gostr(v)},\n" for k, v in sorted(d.items()))
    return f"\t\t{name}: map[string]string{{\n{body}\t\t}},\n"


def ttmap(name: str, d: dict) -> str:
    if not d:
        return f"\t\t{name}: nil,\n"
    body = "".join(f"\t\t\t{gostr(k)}: Tok{v.name},\n" for k, v in sorted(d.items()))
    return f"\t\t{name}: map[string]TokenType{{\n{body}\t\t}},\n"


def strset(name: str, s) -> str:
    if not s:
        return f"\t\t{name}: nil,\n"
    body = "".join(f"\t\t\t{gostr(k)}: {{}},\n" for k in sorted(s))
    return f"\t\t{name}: map[string]struct{{}}{{\n{body}\t\t}},\n"


def ttset(name: str, s) -> str:
    if not s:
        return f"\t\t{name}: nil,\n"
    body = "".join(f"\t\t\tTok{k.name}: {{}},\n" for k in sorted(s, key=lambda m: m.value))
    return f"\t\t{name}: map[TokenType]struct{{}}{{\n{body}\t\t}},\n"


def gen_dialects(Dialect) -> str:
    out = [
        HEADER,
        "// One resolved tokenizer configuration per dialect, read straight off the\n",
        "// reference's tokenizer classes after its own class-building has run, so the\n",
        "// port sees exactly the tables the reference sees -- inherited overrides and\n",
        "// derived maps included.\n\n",
        "package sqlglot\n\n",
        "var dialectConfigs = map[string]*Config{\n",
    ]
    for name in DIALECTS:
        d = Dialect.get_or_raise(name or None)
        tk = d.tokenizer_class
        fmt_strings = {k: v for k, v in tk._FORMAT_STRINGS.items()}
        out.append(f"\t{gostr(name)}: {{\n")
        out.append(f"\t\tName: {gostr(name)},\n")
        out.append(ttmap("SingleTokens", tk.SINGLE_TOKENS))
        out.append(ttmap("Keywords", tk.KEYWORDS))
        out.append(strmap("Quotes", tk._QUOTES))
        if fmt_strings:
            body = "".join(
                f"\t\t\t{gostr(k)}: {{End: {gostr(v[0])}, Type: Tok{v[1].name}}},\n"
                for k, v in sorted(fmt_strings.items())
            )
            out.append(f"\t\tFormatStrings: map[string]FormatString{{\n{body}\t\t}},\n")
        else:
            out.append("\t\tFormatStrings: nil,\n")
        out.append(strmap("Identifiers", tk._IDENTIFIERS))
        # A nil comment end means a line comment; the reference stores None.
        out.append(strmap("Comments", {k: (v or "") for k, v in tk._COMMENTS.items()}))
        out.append(strset("StringEscapes", tk._STRING_ESCAPES))
        out.append(strset("ByteStringEscapes", tk._BYTE_STRING_ESCAPES))
        out.append(strset("IdentifierEscapes", tk._IDENTIFIER_ESCAPES))
        out.append(strset("EscapeFollowChars", tk._ESCAPE_FOLLOW_CHARS))
        out.append(ttset("Commands", tk.COMMANDS))
        out.append(ttset("CommandPrefixTokens", tk.COMMAND_PREFIX_TOKENS))
        out.append(f"\t\tNestedComments: {str(bool(tk.NESTED_COMMENTS)).lower()},\n")
        out.append(f"\t\tHintStart: {gostr(tk.HINT_START)},\n")
        out.append(ttset("TokensPrecedingHint", tk.TOKENS_PRECEDING_HINT))
        out.append(f"\t\tHasBitStrings: {str(bool(tk.BIT_STRINGS)).lower()},\n")
        out.append(f"\t\tHasHexStrings: {str(bool(tk.HEX_STRINGS)).lower()},\n")
        out.append(strmap("NumericLiterals", tk.NUMERIC_LITERALS))
        out.append(strset("VarSingleTokens", tk.VAR_SINGLE_TOKENS))
        out.append(
            "\t\tStringEscapesAllowedInRawStrings: "
            f"{str(bool(tk.STRING_ESCAPES_ALLOWED_IN_RAW_STRINGS)).lower()},\n"
        )
        out.append(f"\t\tHeredocTagIsIdentifier: {str(bool(tk.HEREDOC_TAG_IS_IDENTIFIER)).lower()},\n")
        out.append(f"\t\tHeredocStringAlternative: Tok{tk.HEREDOC_STRING_ALTERNATIVE.name},\n")
        out.append(
            "\t\tNumbersCanBeUnderscoreSeparated: "
            f"{str(bool(d.NUMBERS_CAN_BE_UNDERSCORE_SEPARATED)).lower()},\n"
        )
        out.append(f"\t\tNumbersCanHaveDecimals: {str(bool(tk.NUMBERS_CAN_HAVE_DECIMALS)).lower()},\n")
        out.append(
            f"\t\tIdentifiersCanStartWithDigit: {str(bool(d.IDENTIFIERS_CAN_START_WITH_DIGIT)).lower()},\n"
        )
        out.append(strmap("UnescapedSequences", d.UNESCAPED_SEQUENCES))
        out.append("\t},\n")
    out.append("}\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sqlglot", required=True, type=pathlib.Path)
    ap.add_argument("--out", default="sqlglot", type=pathlib.Path)
    a = ap.parse_args()

    repo = pathlib.Path(__file__).resolve().parent.parent
    sys.path.insert(0, str(a.sqlglot))
    sys.path.insert(0, str(repo / "harness"))
    from oracle import pinned_commit, reference_commit  # noqa: PLC0415

    actual, pinned = reference_commit(a.sqlglot), pinned_commit(repo)
    if actual != pinned:
        raise SystemExit(
            f"reference checkout is at {actual[:12]} but NOTICE pins {pinned[:12]}.\n"
            "The tokenizer tables are part of the pinned surface: check out the "
            "pinned commit, or move the pin deliberately."
        )

    from sqlglot.dialects.dialect import Dialect  # noqa: PLC0415
    from sqlglot.tokenizer_core import TokenType  # noqa: PLC0415

    (a.out / "tokentype_gen.go").write_text(gen_tokentypes(TokenType))
    (a.out / "dialects_gen.go").write_text(gen_dialects(Dialect))
    print(f"reference {actual[:12]}: wrote {a.out}/tokentype_gen.go and {a.out}/dialects_gen.go")
    return 0


if __name__ == "__main__":
    sys.exit(main())
