"""Generate sqlglot/classes_gen.go: which module each expression class lives in.

    python harness/gen_classes.py --sqlglot ~/opensource/sqlglot > sqlglot/classes_gen.go

The reference qualifies a class name by the module it is defined in, and the
dump compares those strings exactly. This table is read from the reference's
own module layout rather than from the committed expectations: a table built
from the corpus only knows the classes the corpus happens to contain, so the
first node the port built outside it -- Nullif, as it turned out -- was
qualified as "core" and diverged. Reading the layout means a class the port
learns to build tomorrow is already spelled correctly.
"""

from __future__ import annotations

import argparse
import collections
import inspect
import pathlib
import sys


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sqlglot", required=True, type=pathlib.Path)
    a = ap.parse_args()

    repo = pathlib.Path(__file__).resolve().parent.parent
    sys.path.insert(0, str(a.sqlglot.expanduser()))
    sys.path.insert(0, str(repo / "harness"))
    from oracle import pinned_commit, reference_commit  # noqa: PLC0415

    actual, pinned = reference_commit(a.sqlglot.expanduser()), pinned_commit(repo)
    if actual != pinned:
        raise SystemExit(f"reference is at {actual[:12]} but NOTICE pins {pinned[:12]}")

    from sqlglot import expressions as exp  # noqa: PLC0415

    prefix = exp.__name__ + "."
    by_module: dict[str, list[str]] = collections.defaultdict(list)
    for name, obj in vars(exp).items():
        if not inspect.isclass(obj) or not issubclass(obj, exp.Expr):
            continue
        if obj.__qualname__ != name:
            continue
        module = obj.__module__
        if not module.startswith(prefix):
            continue
        by_module[module[len(prefix) :]].append(name)

    print("// Code generated by harness/gen_classes.py from the pinned reference. DO NOT EDIT.")
    print("//")
    print("// The module each expression class lives in, in the reference. Dump needs")
    print("// it to qualify class names the way the reference does; a class absent here")
    print('// dumps under "core" and shows up as a mismatch, which is the right failure.')
    print()
    print("package sqlglot")
    print()
    print("var classModule = map[string]string{")
    for module in sorted(by_module):
        print(f"\t// {module}")
        for cls in sorted(by_module[module]):
            print(f'\t"{cls}": "{module}",')
    print("}")

    # The reference's class HIERARCHY, for the rules that dispatch on it.
    # simplify_parens asks whether a node is a Predicate, whether its parent is
    # a Binary, and so on -- questions about ancestry, not about a node's name.
    # Transcribing the answers would be a table that silently rots when the
    # reference reorganises its classes; asking issubclass keeps it honest.
    bases = ("Predicate", "Binary", "Unary", "Condition", "Connector",
             "SubqueryPredicate", "Expr")
    print()
    print("// classIsA[base][class] is true where the reference's class derives")
    print("// from that base. Generated, because it is ancestry rather than naming:")
    print("// a rule that asks \"is this a Predicate\" must get the reference's own")
    print("// answer or it will fold a node the reference leaves alone.")
    print("var classIsA = map[string]map[string]bool{")
    for base in bases:
        base_cls = getattr(exp, base, None)
        if base_cls is None:
            continue
        print(f'\t"{base}": {{')
        for module in sorted(by_module):
            for cls in sorted(by_module[module]):
                obj = getattr(exp, cls, None)
                if obj is not None and isinstance(obj, type) and issubclass(obj, base_cls):
                    print(f'\t\t"{cls}": true,')
        print("\t},")
    print("}")

    print()
    print("// classArgKeys is each class's arg_types in ORDER, which is the order a")
    print("// call's arguments are zipped onto by the reference's from_arg_list, and")
    print("// classVarLen marks the classes whose LAST key collects the rest.")
    print("// Read from the class rather than probed: a builder that only places its")
    print("// arguments is this table, and a hand-written parser that has to place")
    print("// them itself would otherwise have to guess the order.")
    print("var classArgKeys = map[string][]string{")
    for module in sorted(by_module):
        for cls in sorted(by_module[module]):
            obj = getattr(exp, cls, None)
            keys = list(getattr(obj, "arg_types", None) or ())
            if not keys:
                continue
            joined = ", ".join('"%s"' % k for k in keys)
            print(f'\t"{cls}": {{{joined}}},')
    print("}")

    print()
    print("var classVarLen = map[string]bool{")
    for module in sorted(by_module):
        for cls in sorted(by_module[module]):
            obj = getattr(exp, cls, None)
            if getattr(obj, "is_var_len_args", False):
                print(f'\t"{cls}": true,')
    print("}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
