"""Generate sqlglot/classes_gen.go: which module each expression class lives in.

    python harness/gen_classes.py --sqlglot ~/opensource/sqlglot > sqlglot/classes_gen.go

The reference qualifies a class name by the module it is defined in, and the
dump compares those strings exactly. This table is read from the reference's
own module layout rather than from the committed expectations: a table built
from the corpus only knows the classes the corpus happens to contain, so the
first node the port built outside it -- Nullif, as it turned out -- was
qualified as "core" and diverged. Reading the layout means a class the port
learns to build tomorrow is already spelled correctly.
"""

from __future__ import annotations

import argparse
import collections
import inspect
import pathlib
import sys


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sqlglot", required=True, type=pathlib.Path)
    a = ap.parse_args()

    repo = pathlib.Path(__file__).resolve().parent.parent
    sys.path.insert(0, str(a.sqlglot.expanduser()))
    sys.path.insert(0, str(repo / "harness"))
    from oracle import pinned_commit, reference_commit  # noqa: PLC0415

    actual, pinned = reference_commit(a.sqlglot.expanduser()), pinned_commit(repo)
    if actual != pinned:
        raise SystemExit(f"reference is at {actual[:12]} but NOTICE pins {pinned[:12]}")

    from sqlglot import expressions as exp  # noqa: PLC0415

    prefix = exp.__name__ + "."
    by_module: dict[str, list[str]] = collections.defaultdict(list)
    for name, obj in vars(exp).items():
        if not inspect.isclass(obj) or not issubclass(obj, exp.Expr):
            continue
        if obj.__qualname__ != name:
            continue
        module = obj.__module__
        if not module.startswith(prefix):
            continue
        by_module[module[len(prefix) :]].append(name)

    print("// Code generated by harness/gen_classes.py from the pinned reference. DO NOT EDIT.")
    print("//")
    print("// The module each expression class lives in, in the reference. Dump needs")
    print("// it to qualify class names the way the reference does; a class absent here")
    print('// dumps under "core" and shows up as a mismatch, which is the right failure.')
    print()
    print("package sqlglot")
    print()
    print("var classModule = map[string]string{")
    for module in sorted(by_module):
        print(f"\t// {module}")
        for cls in sorted(by_module[module]):
            print(f'\t"{cls}": "{module}",')
    print("}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
