"""Record what the reference's type ANNOTATOR answers, as testdata.

    python harness/gen_annotate.py --sqlglot ~/opensource/sqlglot

sqlglot's annotate_types is 1,112 lines and leans on the optimizer's scope
machinery to resolve a column to a table to a schema. The port has none of
that -- but 56 of the 71 cases in the reference's own annotate_types fixture
need no column at all: a literal has a type, a cast asserts one, an operator
combines the two it is given. That subset is what the port's refusals are
waiting on. `REGEXP_REPLACE` refuses today because deciding whether its last
argument is text means asking the annotator, and for a literal the answer is
local.

So the scope-free cases are recorded here with the reference's answer, the
port is measured against them, and anything needing a column is left out
rather than guessed. Same shape as every other corpus in this repo: the
expectations are committed, so the Go tests need no Python.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys


def load_pairs(sqlglot_dir: pathlib.Path):
    import importlib.util

    spec = importlib.util.spec_from_file_location("h", sqlglot_dir / "tests/helpers.py")
    helpers = importlib.util.module_from_spec(spec)
    sys.modules["h"] = helpers
    spec.loader.exec_module(helpers)
    # Both halves of the contract. annotate_types.sql pins the OPERATORS -- a
    # literal, a cast, a negation -- and annotate_functions.sql pins what each
    # FUNCTION returns, which is the larger half by an order of magnitude and
    # is where the port's type-dependent refusals actually wait.
    out = []
    for name in ("annotate_types", "annotate_functions"):
        out.extend(helpers.load_sql_fixture_pairs(f"optimizer/{name}.sql"))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sqlglot", required=True, type=pathlib.Path)
    ap.add_argument("--out", default="testdata/annotate.json", type=pathlib.Path)
    a = ap.parse_args()
    sys.path.insert(0, str(a.sqlglot))

    import sqlglot
    from sqlglot import exp

    # The dialects the executor configures. The fixture also carries BigQuery
    # cases -- BIGNUMERIC, FLOAT64, ARRAY<STRING> -- and a type the port has no
    # dialect for is not a gap in the port.
    OURS = {"", "tsql", "postgres", "duckdb", "databricks"}

    cases = []
    skipped = 0
    for meta, sql, expected in load_pairs(a.sqlglot):
        # A fixture case may name SEVERAL dialects -- "hive, spark2, spark,
        # databricks" -- and the reference runs it as each. Only the ones this
        # port configures are kept, and the first of those is what it is
        # recorded as.
        named = [d.strip() for d in (meta.get("dialect") or "").split(",")]
        ours = [d for d in named if d in OURS]
        if not ours:
            skipped += 1
            continue
        dialect = ours[0]
        try:
            tree = sqlglot.parse_one(sql, read=dialect or None)
        except Exception:  # noqa: BLE001 -- the reference cannot read it either
            skipped += 1
            continue
        if any(True for _ in tree.find_all(exp.Column)):
            # Needs a column resolved to a table to a schema: that is the
            # optimizer's scope machinery, which is not ported.
            skipped += 1
            continue
        # The reference compares RENDERED types, so `bool` and `BOOLEAN` are
        # the same answer. Record the canonical form rather than the fixture's
        # spelling, or the port would be held to the spelling.
        canonical = exp.DataType.build(expected, dialect=dialect or None).sql(dialect or None)
        cases.append({"sql": sql, "dialect": dialect, "type": canonical})

    # COERCES_TO is the annotator's own table -- which types widen into which
    # -- and it is DATA rather than a closure, so it is emitted rather than
    # probed. `_maybe_coerce(a, b)` returns b when a coerces into b, and a
    # otherwise; that is the whole of binary type resolution.
    from sqlglot.optimizer.annotate_types import TypeAnnotator

    coerces = {
        k.value: sorted(v.value for v in vs)
        for k, vs in TypeAnnotator.COERCES_TO.items()
    }

    a.out.write_text(
        json.dumps({"cases": cases, "coerces_to": coerces}, indent=1, sort_keys=True) + "\n"
    )

    # ... and as a Go table, because the annotator needs it at RUN time and
    # nothing in sqlglot/ reads testdata.
    from sqlglot.dialects.dialect import Dialect

    # Whether a dialect HAS a null type. Where it does not, the reference
    # converts every NULL-typed node to UNKNOWN once inference finishes;
    # where it does -- Databricks, which spells it VOID -- the type survives.
    supports_null = {
        d: bool(Dialect.get_or_raise(d or None).SUPPORTS_NULL_TYPE) for d in sorted(OURS)
    }

    go = [
        "// Code generated by harness/gen_annotate.py from the pinned reference. DO NOT EDIT.\n",
        "//\n",
        "// Which types widen into which. The annotator resolves a binary\n",
        "// operator by asking whether one side coerces into the other; this is\n",
        "// the reference's own COERCES_TO, which is a table rather than a\n",
        "// closure and so is emitted rather than probed.\n",
        "\npackage sqlglot\n\n",
        "var coercesTo = map[string]map[string]bool{\n",
    ]
    for src in sorted(coerces):
        go.append(f'\t"{src}": {{\n')
        for dst in coerces[src]:
            go.append(f'\t\t"{dst}": true,\n')
        go.append("\t},\n")
    go.append("}\n\n")
    go.append("// supportsNullType: where false, a NULL-typed node ends as UNKNOWN.\n")
    go.append("// Databricks is the exception, and spells the surviving type VOID.\n")
    go.append("var supportsNullType = map[string]bool{\n")
    for d, v in supports_null.items():
        go.append(f'\t"{d}": {str(v).lower()},\n')
    go.append("}\n")
    out_go = a.out.parent.parent / "sqlglot" / "annotate_gen.go"
    out_go.write_text("".join(go))
    subprocess.run(["gofmt", "-w", str(out_go)], check=True)
    print(f"  coercion table -> {out_go}")
    print(f"{len(cases)} scope-free annotator cases written to {a.out} ({skipped} need a column)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
