#!/usr/bin/env python3
"""Emit the codepoints Python calls digits that Go's unicode.IsDigit does not.

    python harness/gen_digits.py

The reference decides whether a heredoc tag is a tag at all by calling
`tag.isdigit()`. That is true for Unicode's Numeric_Type=Digit characters --
superscripts, subscripts, circled and parenthesised forms -- as well as the
decimal digits Go's unicode.IsDigit covers, and it is NOT true for the vulgar
fractions.

Go's unicode package exposes neither Numeric_Type nor Python's rule, so this
is generated rather than reasoned about. Two attempts to reason about it were
both wrong: an inclusion list of the superscripts missed the parenthesised
forms, and an exclusion of the fractions from category No got 117 characters
wrong -- mostly script-specific number forms nobody would think to look for.

Depends on the Python that runs it, not on sqlglot: the reference's behaviour
here is Python's, so the version that generates this should be the version the
reference is tested with.
"""

from __future__ import annotations

import pathlib
import sys
import unicodedata


def main() -> int:
    runs: list[tuple[int, int]] = []
    start = prev = None
    for cp in range(0x110000):
        c = chr(cp)
        if c.isdigit() and unicodedata.category(c) != "Nd":
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            runs.append((start, prev))
            start = None
    if start is not None:
        runs.append((start, prev))

    body = "".join("\t{0x%04X, 0x%04X},\n" % (lo, hi) for lo, hi in runs)
    out = pathlib.Path(__file__).resolve().parent.parent / "sqlglot" / "digits_gen.go"
    out.write_text(
        "// Code generated by harness/gen_digits.py. DO NOT EDIT.\n"
        "//\n"
        "// The codepoints Python calls DIGITS that Go's unicode.IsDigit does not.\n"
        "// See harness/gen_digits.py for why this is generated and not reasoned about.\n"
        "\npackage sqlglot\n\n"
        "var digitTypedRanges = [][2]rune{\n" + body + "}\n"
    )
    print(f"{len(runs)} range(s) written to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
